const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom'),babel=require('@babel/core');
const html=fs.readFileSync(path.join(__dirname,'../../index.html'),'utf8');const jsx=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].find(m=>m[1].includes('function AuthView()'))[1].replace(/const root = ReactDOM.createRoot[\s\S]*$/,'window.AuthTest=AuthView; window.PinTest=PersonalCodeForm;');
const w=new JSDOM('<div id="root"></div>',{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true}).window;global.window=w;global.document=w.document;Object.defineProperty(global,'navigator',{value:w.navigator,configurable:true});global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),ReactDOM={...require('react-dom'),...require('react-dom/client')},Simulate=require('react-dom/test-utils').Simulate;w.React=React;w.ReactDOM=ReactDOM;w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});let calls=0,submitted,token;w.fb={auth:{},signIn:async()=>{calls++;throw Error('unavailable');},fx:async(name,args)=>{if(name==='pkPinStatus')return {available:true,playerId:'P123456789'};submitted={name,args};return{token:'test-token',loginId:'P123456789'};},customSignIn:async t=>{token=t;}};w.eval(babel.transformSync(jsx,{plugins:[[require('@babel/plugin-transform-react-jsx'),{runtime:'classic'}]],compact:false}).code);
const root=ReactDOM.createRoot(w.document.getElementById('root'));
const change=async(label,value)=>{const input=w.document.querySelector(`input[aria-label="${label}"]`);assert.ok(input,label);await React.act(()=>Simulate.change(input,{target:{value}}));};
(async()=>{
 await React.act(async()=>root.render(React.createElement(w.AuthTest)));assert.ok(w.document.querySelector('.auth-card'));
 assert.equal(w.document.querySelector('input[autocomplete=tel]'),null);assert.equal(w.document.querySelector('input[autocomplete=one-time-code]'),null);assert.ok(!html.includes('signInWithPhoneNumber'));assert.ok(!html.includes('window.fb.phoneSend'));
 const google=[...w.document.querySelectorAll('button')].find(b=>b.textContent.includes('Google'));await React.act(async()=>google.click());assert.equal(calls,1);assert.ok(w.document.querySelector('[role=alert]'));assert.equal(google.disabled,false);
 await change('קוד שחקן','p123456789');await change('קוד אישי','83492716');await React.act(()=>Simulate.submit(w.document.querySelector('form')));assert.equal(submitted.name,'pkPinLogin');assert.equal(submitted.args.loginId,'P123456789');assert.equal(token,'test-token');
 await React.act(async()=>root.render(React.createElement(w.PinTest,{account:true})));assert.equal(w.document.querySelector('.personal-code-id strong').textContent,'P123456789');
 await change('קוד אישי חדש','19384726');await change('הקלד שוב את הקוד','19384725');submitted=null;await React.act(()=>Simulate.submit(w.document.querySelector('form')));assert.equal(submitted,null);assert.match(w.document.querySelector('[role=alert]').textContent,/אינם זהים/);
 await change('הקלד שוב את הקוד','19384726');await React.act(()=>Simulate.submit(w.document.querySelector('form')));assert.equal(submitted.name,'pkPinEnroll');assert.equal(w.localStorage.getItem('pkLoginId'),'P123456789');
 await React.act(()=>root.unmount());w.close();console.log('PASS: Google retry, no SMS controls/API, player-code login and authenticated PIN enrollment');
})().catch(e=>{console.error(e);w.close();process.exitCode=1;});
