'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const w=new JSDOM('<div id="root"></div>',{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true}).window;
global.window=w;global.document=w.document;
Object.defineProperty(global,'navigator',{value:w.navigator,configurable:true});
global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),ReactDOM={...require('react-dom'),...require('react-dom/client')};
w.React=React;w.ReactDOM=ReactDOM;
w.eval(fs.readFileSync(path.join(__dirname,'../../assets/js/club-ui.js'),'utf8'));
const root=ReactDOM.createRoot(w.document.getElementById('root'));
const render=props=>React.act(()=>root.render(React.createElement(w.ClubUI.SettlementPlayerCards,props)));
(async()=>{
  let resumed;
  const tables=[{id:'mine',players:{me:{},opponent:{}}},{id:'empty',players:{}}];
  await React.act(()=>root.render(React.createElement(w.ClubUI.LobbyOverview,{user:{uid:'me',username:'Test',playerId:'123'},tables,brand:'TEST',locale:'en',onResume:t=>resumed=t})));
  assert.match(w.document.querySelector('.club-lobby-facts').textContent,/Club tables2Occupied seats2Player ID123/);
  await React.act(()=>w.document.querySelector('.club-primary').click());assert.equal(resumed,tables[0]);
  const players=Array.from({length:14},(_,i)=>({uid:'p'+i,username:'Player '+i,playerId:'ID'+i,balance:100+i,agentUid:'a'}));
  const props={players,results:{p0:-25},rakes:{p0:5},members:{a:{username:'Agent'}},logs:[{uid:'p0',at:100,game:'Poker',profit:-25}],period:'Current week'};
  await render(props);assert.equal(w.document.querySelectorAll('.club-account-card').length,12);
  assert.match(w.document.querySelector('.club-account-card').textContent,/Period result\u200e?-25\.00Current balance100\.00Period rake5\.00/);
  const next=[...w.document.querySelectorAll('nav button')].find(b=>b.textContent==='Next');
  await React.act(()=>next.click());assert.equal(w.document.querySelectorAll('.club-account-card').length,2);
  await React.act(()=>[...w.document.querySelectorAll('nav button')].find(b=>b.textContent==='Previous').click());
  let card=w.document.querySelector('.club-account-card');card.focus();await React.act(()=>card.click());
  let modal=w.document.querySelector('[role="dialog"]');assert.ok(modal);assert.match(modal.textContent,/Current balance100\.00Period result\u200e?-25\.00/);
  assert.equal(w.document.activeElement,w.document.querySelector('.club-dialog-close'));
  await React.act(()=>modal.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true})));
  assert.equal(w.document.querySelector('[role="dialog"]'),null);assert.equal(w.document.activeElement,card);
  await React.act(()=>card.click());
  await render({...props,players:[players[13]]});
  assert.equal(w.document.querySelector('[role="dialog"]'),null,'a changed scope closes an out-of-scope account');
  assert.equal(w.document.querySelectorAll('.club-account-card').length,1);
  assert.match(w.document.querySelector('.club-account-card').textContent,/Player 13/);
  await React.act(()=>root.unmount());w.close();
  console.log('PASS: lobby resume, actual seat counts, separate balance/result, account pagination, dialog focus and scope changes');
})().catch(e=>{console.error(e);w.close();process.exitCode=1;});
