'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const w=new JSDOM('<div id="root"></div>',{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true}).window;
global.window=w;global.document=w.document;Object.defineProperty(global,'navigator',{value:w.navigator,configurable:true});global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),ReactDOM={...require('react-dom'),...require('react-dom/client')};w.React=React;w.ReactDOM=ReactDOM;
const frameQueue=new Map();let frameId=0,clock=0;w.requestAnimationFrame=cb=>{frameQueue.set(++frameId,cb);return frameId;};w.cancelAnimationFrame=id=>frameQueue.delete(id);
const mediaListeners=new Set(),media={matches:false,addEventListener:(_,f)=>mediaListeners.add(f),removeEventListener:(_,f)=>mediaListeners.delete(f)};
w.matchMedia=q=>q.includes('prefers-reduced-motion')?media:{matches:false,addEventListener(){},removeEventListener(){}};
const writes=[];w.fb={db:{},auth:{currentUser:{uid:'player'}},getDocs:async()=>({docs:[],forEach(){}}),collection:()=>({}),fx:async(...args)=>{writes.push(args);throw Error('No fixture mutation');}};
const html=fs.readFileSync(require.resolve('../../index.html'),'utf8'),script=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].find(m=>m[1].includes('function ClubsView('))[1].replace(/const root = ReactDOM.createRoot[\s\S]*$/,'window.ClubsTest=ClubsView;');w.eval(script);
const root=ReactDOM.createRoot(w.document.getElementById('root')),entered=[];
const clubs=[{id:'alpha',name:'Alpha',ownerUid:'owner'},{id:'beta',name:'Beta',ownerUid:'owner'},{id:'gamma',name:'Gamma',ownerUid:'owner'}];
const mems=clubs.map((c,i)=>({clubId:c.id,status:'approved',balance:[9953757.32,500.25,75][i]}));
const props={user:{uid:'player',username:'Player'},clubs,myMems:mems,directoryReady:true,onEnter:c=>entered.push(c.id),showToast(){}};
const render=p=>React.act(async()=>root.render(React.createElement(w.ClubsTest,{...props,...p})));
const deck=()=>w.document.querySelector('.cl-deck'),axis=()=>w.document.querySelector('.cl-carousel-axis'),front=()=>w.document.querySelector('.cl-card[data-front=true]'),balance=()=>w.document.querySelector('.cl-balance-amount')?.textContent,enter=()=>w.document.querySelector('.blue-club-orb[role=button]');
const dot=name=>w.document.querySelector('[aria-label="Show '+name+'"]');
const frame=async ms=>React.act(()=>{clock+=ms;const queued=[...frameQueue.values()];frameQueue.clear();queued.forEach(cb=>cb(clock));});
const finish=async()=>{await frame(1);await frame(421);};
const key=k=>React.act(()=>deck().dispatchEvent(new w.KeyboardEvent('keydown',{key:k,bubbles:true,cancelable:true})));
const pointer=async(type,x,y,time)=>{const event=new w.Event(type,{bubbles:true,cancelable:true});Object.defineProperties(event,{pointerId:{value:1},pointerType:{value:'touch'},isPrimary:{value:true},clientX:{value:x},clientY:{value:y},timeStamp:{value:time}});await React.act(()=>deck().dispatchEvent(event));return event;};
(async()=>{
 await render();assert.equal(frameQueue.size,0,'carousel never auto-spins');assert.equal(front().querySelector('.cl-name').textContent,'Alpha');assert.equal(balance(),'9,953,757.32');
 assert.match(axis().style.transform,/translateZ.*rotateY\(0deg\)/,'actual orbit uses a Y-axis with depth compensation');
 const visualCards=[...w.document.querySelectorAll('.cl-card')];
 assert.ok(visualCards.length>clubs.length+1,'small lists have visual loop slots');
 assert.equal(w.document.querySelectorAll('.cl-dots button').length,4,'accessible choices never duplicate');
 assert.ok(Number(visualCards[1].querySelector('.blue-club-orb').style.opacity)>0&&Number(visualCards.at(-1).querySelector('.blue-club-orb').style.opacity)>0,'first club has visible neighbours on both sides');
 assert.match(visualCards[1].style.transform,/rotateY\(45deg\) translateZ/);assert.equal(visualCards[1].querySelector('.blue-club-orb').style.transform,'rotateY(-45deg)','faces counter-rotate instead of becoming thin cards');
 await React.act(()=>visualCards[1].querySelector('.blue-club-orb').click());assert.deepEqual(entered,[],'a neighbour click only selects');assert.equal(enter(),null,'moving clubs cannot be activated');assert.equal(balance(),'9,953,757.32','balance remains attached to settled selection');await React.act(()=>front().querySelector('.blue-club-orb').click());assert.deepEqual(entered,[]);
 await frame(1);await frame(210);assert.notEqual(axis().style.transform,'translateZ(calc(-1 * var(--club-radius))) rotateY(0deg)');assert.equal(balance(),'9,953,757.32');
 await frame(211);assert.equal(front().querySelector('.cl-name').textContent,'Beta');assert.equal(balance(),'500.25');assert.equal(w.document.querySelector('.blue-club-details .sr-only').textContent,'Beta','settled identity is announced with its balance');assert.equal(enter().getAttribute('aria-label'),'Enter Beta');assert.equal(w.document.querySelectorAll('.blue-club-orb[role=button]').length,1,'only the settled front club is accessible for entry');assert.equal(w.document.querySelector('.blue-club-details button.cl-cta'),null,'no separate Enter club button');await React.act(()=>enter().click());assert.deepEqual(entered,['beta']);
 await render({myMems:mems.map(m=>m.clubId==='beta'?{...m,balance:999.99}:m)});assert.equal(front().querySelector('.cl-name').textContent,'Beta');assert.equal(balance(),'999.99','balance refresh never resets orientation');
 await key('Home');await finish();await key('ArrowLeft');await finish();assert.ok(front().classList.contains('cl-card-create'),'left from the first item wraps to Create');assert.equal(w.document.querySelector('.blue-create-club').style.visibility,'hidden','Create reserves the shortcut space so the orbit does not shift');assert.equal(w.document.querySelector('.blue-create-club').tabIndex,-1);
 await key('ArrowRight');await finish();assert.equal(front().querySelector('.cl-name').textContent,'Alpha','right wraps back without a long reverse spin');
 await React.act(()=>enter().dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true})));assert.deepEqual(entered,['beta','alpha']);
 await React.act(()=>enter().dispatchEvent(new w.KeyboardEvent('keydown',{key:' ',bubbles:true,cancelable:true})));assert.deepEqual(entered,['beta','alpha','alpha'],'Enter and Space activate the centered club');
 const before=axis().style.transform;await pointer('pointerdown',200,100,1000);const vertical=await pointer('pointermove',204,155,1100);await pointer('pointerup',204,155,1200);assert.equal(vertical.defaultPrevented,false,'vertical scroll is not captured');assert.equal(axis().style.transform,before);assert.equal(frameQueue.size,0);
 await pointer('pointerdown',260,150,2000);const horizontal=await pointer('pointermove',150,153,2400);assert.equal(horizontal.defaultPrevented,true);assert.notEqual(axis().style.transform,before);assert.equal(enter(),null,'moving clubs cannot be activated');await pointer('pointerup',150,153,2401);await finish();assert.equal(front().querySelector('.cl-name').textContent,'Beta','horizontal drag settles the next club');
 await React.act(()=>front().querySelector('.blue-club-orb').click());assert.equal(frameQueue.size,0,'synthetic click following drag cannot rotate a second time');assert.deepEqual(entered,['beta','alpha','alpha'],'synthetic drag click cannot enter a club');
 await React.act(()=>dot('Gamma').click());assert.ok(frameQueue.size>0);await React.act(()=>{media.matches=true;mediaListeners.forEach(f=>f());});assert.equal(frameQueue.size,0,'enabling reduced motion cancels an in-flight animation');assert.equal(front().querySelector('.cl-name').textContent,'Gamma');
 await key('Home');assert.equal(frameQueue.size,0);assert.equal(front().querySelector('.cl-name').textContent,'Alpha','reduced-motion selection is immediate');
 await render({clubs:[clubs[0]],myMems:[mems[0]]});assert.equal(w.document.querySelectorAll('.cl-dots button').length,2);await key('ArrowLeft');assert.ok(front().classList.contains('cl-card-create'),'one club plus Create loops correctly');await key('ArrowRight');assert.equal(front().querySelector('.cl-name').textContent,'Alpha');
 await render({clubs:[],myMems:[]});assert.equal(w.document.querySelectorAll('.cl-card').length,1);assert.equal(w.document.querySelectorAll('.cl-dots button').length,1);assert.ok(front().classList.contains('cl-card-create'),'empty membership list has a single static Create option');
 assert.equal(writes.length,0,'rotating never changes membership, chips or games');await React.act(()=>root.unmount());assert.equal(frameQueue.size,0);assert.equal(mediaListeners.size,0);w.close();console.log('PASS: real Y-axis carousel, both-side looping, billboard faces, settled balance/entry, drag intent, cyclic keys/dots, small lists and live reduced-motion cleanup');
})().catch(async e=>{console.error(e);await React.act(()=>root.unmount());w.close();process.exitCode=1;});
