'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const w=new JSDOM('<div id="root"></div>',{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true}).window;
global.window=w;global.document=w.document;Object.defineProperty(global,'navigator',{value:w.navigator,configurable:true});global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),ReactDOM={...require('react-dom'),...require('react-dom/client')};w.React=React;w.ReactDOM=ReactDOM;w.PokerRuntime=require('../../assets/js/poker-runtime');w.PokerTournament=require('../../assets/js/poker-tournament');w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});
const actions=[],writes=[],joins=[];const forbidden=async()=>{writes.push(1);throw Error('Unexpected mutation');};
w.fb={db:{},auth:{currentUser:{uid:'viewer',email:'viewer@example.invalid',emailVerified:true}},fx:async(name,args)=>{actions.push({name,args});throw Error('Unexpected callable');},updateDoc:forbidden,addDoc:forbidden,setDoc:forbidden,deleteDoc:forbidden,runTransaction:forbidden,getDocs:async()=>({docs:[]}),getDoc:async()=>({exists:()=>false}),doc:()=>({}),collection:()=>({}),query:()=>({}),where:()=>({}),onSnapshot:()=>()=>{}};
const html=fs.readFileSync(require.resolve('../../index.html'),'utf8'),script=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].find(m=>m[1].includes('function LobbyView('))[1].replace(/const root = ReactDOM.createRoot[\s\S]*$/,'window.LobbyTest=LobbyView;');w.eval(script);
const root=ReactDOM.createRoot(w.document.getElementById('root'));
const players={a:{uid:'a',name:'Human',stack:100,status:'active'},b:{uid:'b',name:'Bot',isBot:true,stack:100,status:'active'}};
const table=(name,phase,patch={})=>({docId:name,clubId:'main',type:'poker',settings:{baseGameType:'NLH',tableName:name,blinds:1,minBuyIn:40,maxPlayers:6},players,gameState:{phase},...patch});
const activePhases=['preflop','flop','turn','river','discard','dc_selection','showdown'];
const active=activePhases.map(phase=>table('active-'+phase,phase));
const waiting=table('waiting-full','waiting',{history:[{at:Date.now()}],players:{...players,c:{uid:'c'},d:{uid:'d'},e:{uid:'e'},f:{uid:'f'}}});
const spin=table('inactive-spin','waiting',{settings:{spinMode:true,spinBuyIn:50,blinds:1,maxPlayers:3}});
const render=tables=>React.act(async()=>root.render(React.createElement(w.LobbyTest,{tablesLoaded:true,user:{uid:'viewer',role:'player',status:'approved',balance:500},tables,tournaments:[],clubSettings:{name:'Netabel'},tab:'poker',setTab(){},onJoinPoker:t=>joins.push(t),onCreatePoker(){},showToast(){}})));
const filters=()=>w.document.querySelector('[aria-label="Poker table filters"]');
const filter=label=>[...filters().querySelectorAll('button')].find(b=>b.textContent.trim()===label);
const names=()=>[...w.document.querySelectorAll('.tbl-row:not(.tbl-spin) .tbl-name')].map(e=>e.textContent).sort();
(async()=>{
 await render([...active,waiting,table('unknown','idle'),table('missing',undefined),table('empty-stale','flop',{players:{}}),table('departed-stale','flop',{players:{a:players.a,b:{...players.b,left:true},c:{uid:'c',status:'left'}}}),table('other-club','flop',{clubId:'private'}),spin,table('tour-table','flop',{tournamentId:'tour'})]);
 assert.equal(filters().dir,'ltr','filter strip starts physically at the left in RTL layouts');
 assert.equal(filters().firstElementChild.textContent.trim(),'LIVE','LIVE is the first filter');
 assert.equal(filter('All').getAttribute('aria-pressed'),'true','All remains the default');
 assert.ok(names().includes('waiting-full'),'default view still includes waiting tables');
 await React.act(()=>filter('LIVE').click());
 assert.deepEqual(names(),activePhases.map(phase=>'active-'+phase).sort(),'LIVE includes actual hand/game phases, not full waiting tables, recent-history-only tables, empty/departed seats, unknown phases, other clubs, spins or tournaments');
 assert.equal(filter('LIVE').getAttribute('aria-pressed'),'true');
 assert.equal(w.document.querySelector('.tbl-spin'),null,'inactive spins are absent');
 assert.equal([...w.document.querySelectorAll('h2')].some(h=>/Spin & Cash|Tournaments/.test(h.textContent)),false,'irrelevant sections do not remain beneath LIVE');
 await render([waiting,spin]);
 assert.equal(names().length,0);
 assert.match(w.document.body.textContent,/No live tables right now/,'no active hand has a clear empty state');
 await render([{...waiting,gameState:{phase:'flop'}},spin]);
 assert.deepEqual(names(),['waiting-full'],'a real phase update adds the table without toggling or refresh');
 await React.act(()=>filter('All').click());
 assert.equal(filter('All').getAttribute('aria-pressed'),'true');
 assert.deepEqual(names(),['waiting-full'],'All restores the unfiltered ring list');
 assert.ok(w.document.querySelector('.tbl-spin'),'All restores Spin section');
 assert.equal(actions.length,0,'filtering issues no game/server commands');assert.equal(writes.length,0);assert.equal(joins.length,0,'filter clicks never enter a table');
 await React.act(()=>root.unmount());w.close();console.log('PASS: leftmost LIVE filter, truthful active phases, waiting/stale exclusions, live updates, empty state, All restoration and zero game actions');
})().catch(async e=>{console.error(e);await React.act(()=>root.unmount());w.close();process.exitCode=1;});
