'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const w=new JSDOM('<div id="root"></div>',{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true}).window;
global.window=w;global.document=w.document;Object.defineProperty(global,'navigator',{value:w.navigator,configurable:true});global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),ReactDOM={...require('react-dom'),...require('react-dom/client')};w.React=React;w.ReactDOM=ReactDOM;
w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});w.PokerRuntime=require('../../assets/js/poker-runtime');
const cards=['A','K','Q','J','10','9'].map((val,i)=>({id:'c'+i,val,suit:['♠','♥','♦','♣'][i%4]}));
let current={settings:{serverEngine:false,maxPlayers:6,baseGameType:'Omaha6',actionTime:30,blinds:5},gameState:{__seq:1,phase:'preflop',activeTurnUid:'me',turnStartedAt:Date.now(),highestBet:10,minRaise:10,board:[],pots:[],currentGameType:'Omaha6',handN:1},players:{me:{uid:'me',name:'Me',stack:100,bet:0,cards,status:'active',seatIndex:0,lastSeen:Date.now()},other:{uid:'other',name:'Other',stack:200,bet:10,cards:[],status:'active',seatIndex:1,lastSeen:Date.now(),actionText:'Check'}}};
const ref=(...args)=>({id:args.at(-1),path:args.slice(1).join('/')});let tableNext,tableFail,writes=[],messages=[];
const snapshot=()=>({id:'test-table',exists:()=>true,data:()=>structuredClone(current),metadata:{fromCache:false}});
w.fb={db:{},doc:ref,collection:ref,query:r=>r,where:()=>({}),fx:async()=>({}),getDoc:async()=>({exists:()=>false}),getDocs:async()=>({docs:[]}),updateDoc:async()=>{},setDoc:async()=>{},addDoc:async()=>({id:'x'}),deleteDoc:async()=>{},onSnapshot:(r,opts,next,error)=>{const cb=typeof opts==='function'?opts:next;if(r.path==='tables/test-table'){tableNext=cb;tableFail=error;queueMicrotask(()=>cb(snapshot()));}else queueMicrotask(()=>cb({exists:()=>false,docs:[]}));return()=>{};},runTransaction:async(_,fn)=>fn({get:async()=>snapshot(),update:(r,data)=>{writes.push(data);current={...current,...data};}})};
const html=fs.readFileSync(path.join(__dirname,'../../index.html'),'utf8');const source=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].find(m=>m[1].includes('function PokerTable('))[1].replace(/const root = ReactDOM.createRoot[\s\S]*$/,'window.TableTest=PokerTable;');w.eval(source);w.__pkMuted=true;
const root=ReactDOM.createRoot(w.document.getElementById('root'));
(async()=>{await React.act(async()=>root.render(React.createElement(w.TableTest,{tableDocId:'test-table',user:{uid:'me',role:'player',balance:500,playerId:'P123456789'},clubSettings:{},onLeave(){},showToast:m=>messages.push(m)})));
 const doc=w.document,dock=doc.querySelector('.poker-action-dock');assert.ok(dock);assert.equal(dock.parentElement.classList.contains('poker-room'),true);assert.equal(dock.closest('.pt-stage'),null);
 const hero=doc.querySelector('.poker-seat-hero');assert.equal(hero.querySelectorAll('.card-face').length,6);assert.equal(hero.querySelectorAll('.poker-hole-cards span[style*="margin-left: -"]').length,0);assert.ok(doc.querySelector('.poker-player-info .poker-seat-action'));
 const call=[...dock.querySelectorAll('button')].find(b=>b.textContent.includes('CALL'));assert.ok(call);current.players.me.stack=150;
 await React.act(async()=>call.click());assert.equal(writes.length,0);assert.equal(current.players.me.stack,150);assert.ok(messages.some(m=>m.includes('table updated')));
 await React.act(()=>tableFail({code:'permission-denied'}));assert.ok(doc.querySelector('.poker-connection-status'));assert.ok(doc.querySelector('.poker-seat-hero'));assert.equal(doc.querySelector('.poker-seat-hero .poker-player-info').textContent.includes('100'),true);
 await React.act(()=>root.unmount());w.close();console.log('PASS: actual Omaha6 hand, separate action dock, protected top-up and recoverable snapshot failure');
})().catch(async e=>{console.error(e);try{await React.act(()=>root.unmount());}catch(_){}w.close();process.exitCode=1;});
