'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const w=new JSDOM('<div id="root"></div>',{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true}).window;
global.window=w;global.document=w.document;Object.defineProperty(global,'navigator',{value:w.navigator,configurable:true});global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),ReactDOM={...require('react-dom'),...require('react-dom/client')};w.React=React;w.ReactDOM=ReactDOM;
w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});w.PokerRuntime=require('../../assets/js/poker-runtime');
const cards=['A','K','Q','J','10','9'].map((val,i)=>({id:'c'+i,val,suit:['♠','♥','♦','♣'][i%4]}));
let current={settings:{serverEngine:false,maxPlayers:6,baseGameType:'Omaha6',actionTime:30,blinds:5},gameState:{__seq:1,phase:'preflop',activeTurnUid:'me',turnStartedAt:Date.now(),highestBet:10,minRaise:10,board:[],pots:[],currentGameType:'Omaha6',handN:1},players:{me:{uid:'me',name:'Me',stack:100,bet:0,cards,status:'active',seatIndex:0,lastSeen:Date.now()},other:{uid:'other',name:'Other',stack:200,bet:10,cards:[],status:'active',seatIndex:1,lastSeen:Date.now(),actionText:'Check'}}};
let privateHand=[],fxCalls=[];
const ref=(...args)=>({id:args.at(-1),path:args.slice(1).join('/')});let tableNext,tableFail,writes=[],messages=[];
const snapshot=()=>({id:'test-table',exists:()=>true,data:()=>structuredClone(current),metadata:{fromCache:false}});
w.fb={db:{},doc:ref,collection:ref,query:r=>r,where:()=>({}),fx:async(name,args)=>{fxCalls.push({name,args});return{};},getDoc:async()=>({exists:()=>false}),getDocs:async()=>({docs:[]}),updateDoc:async()=>{},setDoc:async()=>{},addDoc:async()=>({id:'x'}),deleteDoc:async()=>{},onSnapshot:(r,opts,next,error)=>{const cb=typeof opts==='function'?opts:next;if(r.path==='tables/test-table'){tableNext=cb;tableFail=error;queueMicrotask(()=>cb(snapshot()));}else if(r.path==='tables/test-table/priv/me') queueMicrotask(()=>cb({exists:()=>true,data:()=>({cards:privateHand})}));else queueMicrotask(()=>cb({exists:()=>false,docs:[]}));return()=>{};},runTransaction:async(_,fn)=>fn({get:async()=>snapshot(),update:(r,data)=>{writes.push(data);current={...current,...data};}})};
const html=fs.readFileSync(path.join(__dirname,'../../index.html'),'utf8');const source=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].find(m=>m[1].includes('function PokerTable('))[1].replace(/const root = ReactDOM.createRoot[\s\S]*$/,'window.TableTest=PokerTable;');w.eval(source);w.__pkMuted=true;
const root=ReactDOM.createRoot(w.document.getElementById('root'));
(async()=>{await React.act(async()=>root.render(React.createElement(w.TableTest,{tableDocId:'test-table',user:{uid:'me',role:'player',balance:500,playerId:'P123456789'},clubSettings:{},onLeave(){},showToast:m=>messages.push(m)})));
 const doc=w.document,dock=doc.querySelector('.poker-action-dock');assert.ok(dock);assert.equal(dock.parentElement.classList.contains('poker-room'),true);assert.equal(dock.closest('.pt-stage'),null);
 const hero=doc.querySelector('.poker-seat-hero');assert.equal(hero.querySelectorAll('.card-face').length,6);assert.equal(hero.querySelector('.poker-own-fan').children.length,6);assert.ok([...hero.querySelector('.poker-own-fan').children].every(c=>c.style.transform.includes('rotate(')));assert.ok(doc.querySelector('.poker-player-info .poker-seat-action'));
 current.players.other.cards=cards;
 await React.act(async()=>tableNext(snapshot()));
 let opponent=doc.querySelector('.poker-seat:not(.poker-seat-hero) .poker-opponent-fan');
 assert.equal(opponent.querySelectorAll('.card-back').length,6,'opponents have six distinct backs in a compact fan');
 assert.equal(opponent.children.length,6);
 assert.equal(doc.querySelector('.poker-seat-hero .poker-opponent-fan'),null,'own hand stays separate and fully readable');
 current.gameState.allInReveal=true;
 await React.act(async()=>tableNext(snapshot()));
 opponent=doc.querySelector('.poker-seat:not(.poker-seat-hero) .poker-opponent-fan');
 assert.equal(opponent.querySelectorAll('.card-face').length,6,'revealed opponent hands keep all six cards');
 assert.equal(opponent.children.length,6,'revealing cards keeps a single fan');
 assert.ok([...opponent.children].every(c=>c.style.transform.includes('rotate(')),'revealed cards retain their fan angles');
 current.gameState.allInReveal=false;
 await React.act(async()=>tableNext(snapshot()));
 const saved=structuredClone(current);
 const heart=val=>({val,suit:'♥'});
 current.players.me.cards=[heart('A'),heart('K'),{val:'Q',suit:'♣'},{val:'J',suit:'♦'},{val:'9',suit:'♣'},{val:'8',suit:'♦'}];
 current.players.other.cards=[{val:'A',suit:'♠'},{val:'A',suit:'♦'},{val:'K',suit:'♣'},{val:'K',suit:'♦'},{val:'7',suit:'♣'},{val:'6',suit:'♠'}];
 current.gameState={...current.gameState,phase:'showdown',activeTurnUid:null,lastWinners:'Me',board:[heart('Q'),heart('J'),heart('10'),{val:'2',suit:'♣'},{val:'3',suit:'♦'}]};
 const winningHand=current.players.me.cards;
 for(const variant of ['NLH','Omaha4','Omaha6']) {
   current.players.me.cards=winningHand.slice(0,variant==='NLH'?2:variant==='Omaha4'?4:6);
   current.gameState.currentGameType=variant;
   await React.act(async()=>tableNext(snapshot()));
   assert.equal(doc.querySelectorAll('.poker-board-primary [data-winning-card]').length,3,variant+' highlights the three winning board cards');
   assert.equal(doc.querySelectorAll('.poker-seat-hero [data-winning-card]').length,2,variant+' highlights the two winning hole cards');
   assert.equal(doc.querySelectorAll('.poker-seat:not(.poker-seat-hero) [data-winning-card]').length,0,'loser cards are not highlighted');
   assert.ok(doc.querySelector('.poker-seat-hero.poker-seat-winner .winner-glow'));
   assert.match(doc.querySelector('.poker-seat-hero .poker-hand-name').textContent,/Straight Flush/i);
   assert.equal(doc.querySelector('.poker-seat-winner .card-mucked'),null,'winning cards never fade into the muck');
 }
 privateHand=current.players.me.cards;
 current.players.me.cardCount=6;current.players.me.cards=[];current.settings.serverEngine=true;
 await React.act(async()=>tableNext(snapshot()));
 assert.equal(doc.querySelectorAll('.poker-seat-hero .card-face').length,6,'server private hand remains visible');
 assert.equal(doc.querySelectorAll('.poker-seat-hero [data-winning-card]').length,2,'server private winner hand stays highlighted');
 current=structuredClone(saved);
 await React.act(async()=>tableNext(snapshot()));
 privateHand=[{val:'2',suit:'♠'},{val:'A',suit:'♥'},{val:'K',suit:'♦'}];
 current.settings.serverEngine=true;current.players.me.cardCount=3;current.players.me.cards=[];current.gameState.phase='discard';
 await React.act(async()=>tableNext(snapshot()));
 const firstCard=doc.querySelector('.poker-own-fan').firstElementChild;
 assert.equal(firstCard.querySelector('.poker-card-index>span').textContent,'A');
 await React.act(async()=>firstCard.click());
 assert.deepEqual(fxCalls.find(c=>c.name==='pkDiscard').args.index,1,'sorted Pineapple discard uses the original deal index');
 current=structuredClone(saved);await React.act(async()=>tableNext(snapshot()));
 const call=[...dock.querySelectorAll('button')].find(b=>b.textContent.includes('CALL'));assert.ok(call);current.players.me.stack=150;
 await React.act(async()=>call.click());assert.equal(writes.length,0);assert.equal(current.players.me.stack,150);assert.ok(messages.some(m=>m.includes('table updated')));
 await React.act(async()=>tableFail({code:'permission-denied'}));assert.ok(doc.querySelector('.poker-connection-status'));assert.ok(doc.querySelector('.poker-seat-hero'));assert.equal(doc.querySelector('.poker-seat-hero .poker-player-info').textContent.includes('100'),true);
 await React.act(async()=>root.unmount());w.close();console.log('PASS: readable own Omaha6 fan, NLH/Omaha winning cards and names, private server hands, compact hidden/revealed opponent fans, separate action dock, protected top-up and recoverable snapshot failure');
})().catch(async e=>{console.error(e);try{await React.act(async()=>root.unmount());}catch(_){}w.close();process.exitCode=1;});
