'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const w=new JSDOM('<div id="root"></div>',{url:'https://pokerten.com/',runScripts:'outside-only',pretendToBeVisual:true}).window;global.window=w;global.document=w.document;Object.defineProperty(global,'navigator',{value:w.navigator,configurable:true});global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),ReactDOM=require('react-dom/client'),{Simulate}=require('react-dom/test-utils');w.React=React;w.eval(fs.readFileSync(require.resolve('../../assets/js/poker-settlement-ui.js'),'utf8'));const root=ReactDOM.createRoot(w.document.getElementById('root')),doc=w.document,fixture=require('./settlement-fixture.cjs');
const text=node=>node.textContent.replace(/[\u200e\u200f]/g,'');
let data,calls=[];const call=async(name,args)=>{calls.push({name,args});if(name==='pkSettlementReport')return structuredClone(data);if(name==='pkSettlement')return{ok:true};if(name==='pkSettlementTerms')return{role:'owner',members:[{uid:'player',name:'שחקן ללא רייקבק',role:'player',status:'approved',primaryAgentId:'agent',rakebackPct:0},{uid:'agent',name:'סוכן א׳',role:'agent',status:'approved',agentPct:50}]};throw Error('Unexpected request '+name);};
const mount=role=>React.act(async()=>root.render(React.createElement(w.PokerSettlement.Settlement,{key:role,user:{uid:role==='owner'?'owner':'player',role},clubId:'club',call})));
(async()=>{
 data=fixture('player','player');await mount('player');assert.doesNotMatch(doc.body.textContent,/רייקבק|רייק|עמלה|סוכנים ואחוזים|ניהול מחזורים/);assert.match(doc.body.textContent,/340\.17/);assert.equal(doc.querySelectorAll('.st-metric').length,3);
 // The current cycle wins even when the API contains a conflicting lifetime total.
 data.chips=4757;data.totalResult=-20157;data.player.totals.result=0;await mount('player-zero-cycle');
 const chipMetric=()=>[...doc.querySelectorAll('.st-metric')].find(n=>n.textContent.includes('צ׳יפים כעת'));
 assert.match(chipMetric().textContent,/במחזור הנוכחי/);assert.match(text(chipMetric().querySelector('strong')),/47\.57 \(0\.00\)/);
 assert.doesNotMatch(doc.body.textContent,/201\.57|מצטבר|תוצאה כללית|כל המחזורים/);
 assert.equal(doc.querySelector('option[value="all"]'),null,'player cannot select an aggregate lifetime report');
 data.player.totals.result=50000;await mount('player-winning-cycle');assert.match(text(chipMetric().querySelector('strong')),/\(\+500\.00\)/);
 data.cycle={...data.cycle,id:'closed_cycle',number:0,status:'closed'};data.cycles=[data.cycle,{...data.cycle,id:data.currentCycleId,number:1,status:'open'}];data.player.totals.result=-20000;await mount('player-closed-cycle');
 assert.match(chipMetric().textContent,/במחזור שנבחר/);assert.match(text(chipMetric().querySelector('strong')),/47\.57 \(-200\.00\)/);assert.doesNotMatch(doc.body.textContent,/201\.57|תוצאה כללית/);
 data=fixture('player','player');data.player.hasRakeback=true;data.player.rakebackTotal=200;await mount('rb');assert.match(doc.body.textContent,/הרייקבק שלי/);assert.equal(doc.querySelectorAll('.st-metric').length,4);
 data=fixture('agent','player');data.currentTotals={chips:4757,totalResult:-20157};data.agent.playersResult=0;data.details[0].totals.result=0;data.funds[0]={uid:'other',balance:4757,totalResult:-20157};await mount('agent');
 assert.match(text(chipMetric().querySelector('strong')),/47\.57 \(0\.00\)/);assert.match(text(chipMetric().querySelector('small')),/תוצאה כללית: -201\.57/);
 const peopleRow=[...doc.querySelectorAll('tbody tr')].find(n=>n.textContent.includes('Other human player'));assert.match(text(peopleRow.children[1]),/47\.57 \(0\.00\)/);assert.match(text(peopleRow.querySelector('small')),/תוצאה כללית: -201\.57/);
 assert.match(doc.body.textContent,/רייק שנוצר|העמלה שלי/);assert.doesNotMatch(doc.body.textContent,/ניהול מחזורים|סוכנים ואחוזים/);
 data=fixture('owner','owner');data.currentTotals={chips:80000,totalResult:-61933};data.club.totals.playersResult=-20000;await mount('owner');
 assert.match(text(chipMetric().querySelector('strong')),/800\.00 \(-200\.00\)/);assert.match(text(chipMetric().querySelector('small')),/תוצאה כללית: -619\.33/);
 assert.match(doc.body.textContent,/ניהול מחזורים/);assert.match(doc.body.textContent,/Other human player/);
 const buttons=()=>[...doc.querySelectorAll('button')];await React.act(()=>buttons().find(b=>b.textContent==='רישום תשלום').click());const dialog=doc.querySelector('[role="dialog"]');assert.ok(dialog);await React.act(()=>Simulate.change(dialog.querySelector('input[type=number]'),{target:{value:'50.25'}}));await React.act(async()=>Simulate.submit(dialog));assert.equal(calls.findLast(c=>c.name==='pkSettlement').args.amount,50.25);assert.equal(calls.findLast(c=>c.name==='pkSettlement').args.action,'payment');
 const legacyPlayer={uid:'player',name:'שחקן',balance:80000,onTables:0,chips:80000,result:-20000,totalResult:-19600,openSessions:0};
 data={active:false,legacy:true,role:'player',canClose:false,cycle:{id:'legacy_current',number:0,status:'open',startAt:Date.now()-86400000,endAt:null},cycles:[],currentCycleId:'legacy_current',legacyReport:{players:[legacyPlayer],totals:legacyPlayer,asOf:Date.now()}};await mount('legacy-player');
 assert.match(doc.body.textContent,/המחזור הנוכחי · פתוח/);assert.match(doc.body.textContent,/800\.00/);assert.match(doc.body.textContent,/-200\.00/);assert.doesNotMatch(doc.body.textContent,/רייק|עמלה|פתיחת המחזור החדש|סגירת המחזור|196\.00|כללית|מצטבר/);
 assert.match(text(doc.querySelector('.st-net strong')),/800\.00 \(-200\.00\)/);
 data.legacyReport.totals={...legacyPlayer,result:0};await mount('legacy-player-zero');assert.match(text(doc.querySelector('.st-net strong')),/800\.00 \(0\.00\)/);assert.doesNotMatch(doc.body.textContent,/196\.00|כללית|מצטבר/);
 data.cycle={...data.cycle,status:'closed',endAt:Date.now()};await mount('legacy-player-closed');assert.match(doc.body.textContent,/במחזור שנבחר|בזמן הסגירה/);assert.doesNotMatch(doc.body.textContent,/התוצאה שלי במחזור הנוכחי|196\.00/);
 data.cycle={...data.cycle,status:'open',endAt:null};
 data={...data,role:'owner',canClose:true,legacyReport:{...data.legacyReport,totals:{...legacyPlayer,rake:2000,commission:1400},agents:[]}};await mount('legacy-owner');assert.match(text(doc.querySelector('.st-net strong')),/800\.00 \(-200\.00\)/);assert.match(text(doc.querySelector('.st-net .st-lifetime-note')),/כללית: -196\.00/);assert.match(doc.body.textContent,/סגירת המחזור ופתיחת הבא/);assert.doesNotMatch(doc.body.textContent,/פתיחת המחזור החדש/);
 const commandCount=calls.filter(c=>c.name==='pkSettlement').length;w.confirm=()=>false;await React.act(()=>buttons().find(b=>b.textContent==='סגירת המחזור ופתיחת הבא').click());assert.equal(calls.filter(c=>c.name==='pkSettlement').length,commandCount);
 let confirmation='';w.confirm=text=>{confirmation=text;return true;};await React.act(async()=>buttons().find(b=>b.textContent==='סגירת המחזור ופתיחת הבא').click());assert.equal(calls.findLast(c=>c.name==='pkSettlement').args.action,'closeLegacy');assert.match(confirmation,/הנוכחי יישמר|לא ישתנו|לא יועברו/);
 await React.act(async()=>root.render(React.createElement(w.PokerSettlement.SettlementMembers,{clubId:'club',call})));assert.match(doc.body.textContent,/סוכנים ואחוזים/);assert.doesNotMatch(doc.body.textContent,/תוצאות שחקנים|יתרה להתחשבנות/);await React.act(()=>buttons().find(b=>b.textContent==='תנאים').click());assert.match(doc.body.textContent,/סוכן אחראי|רייקבק לשחקן/);
 await React.act(()=>root.unmount());w.close();console.log('PASS: current/selected-cycle result before lifetime, zero and positive cycle results, player lifetime/word privacy, role-specific reports and payment/terms flows');
})().catch(async e=>{console.error(e);await React.act(()=>root.unmount());w.close();process.exitCode=1;});
