'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const w=new JSDOM('<div id="root"></div>',{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true}).window;
global.window=w;global.document=w.document;Object.defineProperty(global,'navigator',{value:w.navigator,configurable:true});global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),ReactDOM={...require('react-dom'),...require('react-dom/client')};w.React=React;w.ReactDOM=ReactDOM;w.PokerRuntime=require('../../assets/js/poker-runtime');w.PokerTournament=require('../../assets/js/poker-tournament');w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});
const calls=[],messages=[];let next,settle,created=0,newTables=0;
const current={authorityVersion:2,clubId:'main',settings:{serverEngine:true,maxPlayers:6,baseGameType:'NLH',blinds:1,minBuyIn:40,maxBuyIn:200,straddle:true},players:{},gameState:{phase:'waiting',pots:[],board:[],__seq:1}};
const ref=(...a)=>({path:a.slice(1).join('/')});w.fb={db:{},auth:{currentUser:{uid:'viewer'}},doc:ref,collection:ref,query:r=>r,where:()=>({}),getDoc:async()=>({exists:()=>false}),getDocs:async()=>({docs:[]}),fx:(name,args)=>{if(name==='pkTick')return Promise.resolve({});calls.push({name,args});return new Promise((resolve,reject)=>{settle={resolve,reject};});},onSnapshot:(r,opts,fn)=>{const cb=typeof opts==='function'?opts:fn;if(r.path==='tables/test'){next=cb;queueMicrotask(()=>cb({id:'test',exists:()=>true,data:()=>structuredClone(current),metadata:{fromCache:false}}));}else queueMicrotask(()=>cb({exists:()=>false,docs:[]}));return()=>{};}};
const html=fs.readFileSync(require.resolve('../../index.html'),'utf8'),script=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].find(m=>m[1].includes('function PokerTable('))[1].replace(/const root = ReactDOM.createRoot[\s\S]*$/,'window.TableTest=PokerTable;window.CreateTest=PokerCreateView;');w.eval(script);w.__pkMuted=true;
const root=ReactDOM.createRoot(w.document.getElementById('root')),doc=w.document,byTitle=t=>doc.querySelector('button[title="'+t+'"]');
const render=async role=>React.act(async()=>root.render(React.createElement(w.TableTest,{key:role,tableDocId:'test',user:{uid:'viewer',role,managedGames:[],balance:1000},clubSettings:{},onLeave(){},onCreateTable(){newTables++;},showToast:(m,type)=>messages.push({m,type})})));
const menu=async()=>React.act(()=>byTitle('Table menu').click());
(async()=>{
 await render('player');await React.act(()=>[...doc.querySelectorAll('button')].find(b=>b.textContent.trim()==='Spectate the table').click());
 assert.equal(doc.querySelector('.poker-spectator-seat'),null,'open tables use the black seat controls without a duplicate floating Take a seat');
 const emptySeat=doc.querySelector('button[aria-label="Take seat 2"]');assert.ok(emptySeat,'the real empty seat remains clickable');
 await React.act(()=>emptySeat.click());assert.match(doc.querySelector('[role="dialog"]').textContent,/Seat 2 — buy-in/,'the chosen seat opens the buy-in confirmation');assert.equal(calls.length,0,'choosing a seat never buys in without confirming the amount');
 await React.act(()=>[...doc.querySelectorAll('button')].find(b=>b.textContent.trim()==='Spectate the table').click());assert.ok(byTitle('Table menu'));await menu();
 assert.ok(byTitle('Sound on/off'));for(const t of ['Add chips','Sit out','Add bot','Fill empty seats with bots','Create a new table','Edit table settings'])assert.equal(byTitle(t),null,t+' is unavailable to a regular spectator');assert.equal(calls.length,0);
 for(const role of ['club_owner','manager','super_admin']){
  await render(role);await React.act(()=>[...doc.querySelectorAll('button')].find(b=>b.textContent.trim()==='Spectate the table').click());await menu();
  const fill=byTitle('Fill empty seats with bots');assert.ok(fill);assert.ok(byTitle('Add bot'));assert.ok(byTitle('Create a new table'));assert.equal(byTitle('Add chips'),null);
  const before=calls.length;await React.act(async()=>{fill.click();fill.click();});assert.equal(calls.length,before+1);assert.equal(calls.at(-1).args.op,'fillbots');assert.equal(calls.at(-1).args.tableId,'test');
  await React.act(async()=>settle.reject(new Error('Insufficient club funds')));assert.equal(messages.at(-1).m,'Insufficient club funds');
  await menu();await React.act(async()=>byTitle('Fill empty seats with bots').click());await React.act(async()=>settle.resolve({ok:true,added:6}));assert.match(messages.at(-1).m,/6 bots/);
  await menu();await React.act(()=>byTitle('Create a new table').click());
 }
 assert.equal(newTables,3);
 w.fb.auth.currentUser={uid:'viewer',email:'aaci.yoni@gmail.com',emailVerified:true};
 const baseFx=w.fb.fx,board=['A','K','Q','J','10'].map(val=>({val,suit:'♠'}));w.fb.fx=(name,args)=>name==='godPeek'?Promise.resolve({tableId:args.tableId,contextKey:args.contextKey,hands:{},finalBoard:board}):baseFx(name,args);
 current.gameState={phase:'preflop',activeTurnUid:'other',turnStartedAt:Date.now(),highestBet:2,minRaise:2,handN:1,__seq:2,pots:[],board:[]};current.players={other:{uid:'other',name:'Other',isBot:false,stack:98,bet:2,cards:[],cardCount:2,status:'active',seatIndex:3},bot:{uid:'bot',name:'Robot',isBot:true,stack:100,bet:0,cards:[],cardCount:2,status:'active',seatIndex:1}};
 const kindBadges=()=>doc.querySelectorAll('.poker-god-player-kind');
 await render('player');await render('super_admin');const watch=[...doc.querySelectorAll('button')].find(b=>b.textContent.trim()==='Spectate the table');if(watch)await React.act(()=>watch.click());
 assert.equal(kindBadges().length,0,'an authorized account sees no identity badges while GOD mode is off');
 await menu();await React.act(async()=>byTitle('GOD view').click());
 const preview=doc.querySelector('.poker-board-primary');assert.ok(preview);assert.equal(preview.querySelectorAll('.poker-god-future-card').length,5);assert.equal(doc.querySelector('.poker-god-runout'),null,'future cards use the actual board slots, never a header');
 assert.equal(kindBadges().length,2,'GOD mode labels both occupied seats');
 const botBadge=doc.querySelector('.poker-god-player-kind.is-bot'),humanBadge=doc.querySelector('.poker-god-player-kind.is-human');
 assert.equal(botBadge.getAttribute('aria-label'),'בוט');assert.equal(botBadge.getAttribute('role'),'img');assert.equal(botBadge.parentElement.querySelector('.truncate').textContent,'Robot');
 assert.equal(humanBadge.getAttribute('aria-label'),'שחקן אנושי');assert.equal(humanBadge.getAttribute('role'),'img');assert.equal(humanBadge.parentElement.querySelector('.truncate').textContent,'Other');
 assert.equal(botBadge.parentElement.classList.contains('poker-player-name'),true,'the badge stays in the name row, outside card and balance rows');
 await menu();await React.act(async()=>byTitle('GOD view').click());assert.equal(kindBadges().length,0,'turning GOD mode off removes identity badges from the DOM');
 await menu();await React.act(async()=>byTitle('GOD view').click());assert.equal(kindBadges().length,2);
 w.fb.auth.currentUser.emailVerified=false;await render('super_admin');
 assert.equal(kindBadges().length,0,'revoking verification hides badges on the existing component without changing its role or UID');
 assert.equal(doc.querySelector('.poker-god-future-card'),null,'unverified spectator cannot retain the privileged preview');
 await menu();assert.equal(byTitle('GOD view'),null);await menu();
 w.fb.auth.currentUser={uid:'viewer',email:'ordinary-admin@example.invalid',emailVerified:true};await render('super_admin');
 assert.equal(kindBadges().length,0,'a super_admin role does not authorize GOD identity badges');await menu();assert.equal(byTitle('GOD view'),null);await menu();
 w.fb.auth.currentUser={uid:'different-user',email:'aaci.yoni@gmail.com',emailVerified:true};await render('super_admin');
 assert.equal(kindBadges().length,0,'an allowlisted identity for another UID cannot retain GOD identity badges');await menu();assert.equal(byTitle('GOD view'),null);await menu();
 w.fb.fx=baseFx;

 await React.act(async()=>root.render(React.createElement(w.CreateTest,{user:{uid:'viewer',role:'club_owner'},clubSettings:{},onBack(){},onCreated(){created++;},showToast:(m,type)=>messages.push({m,type})})));
 const select=doc.querySelector('[aria-label="Bots at table creation"]');assert.ok([...select.options].some(o=>o.value==='full'));await React.act(()=>{select.value='full';select.dispatchEvent(new w.Event('change',{bubbles:true}));});
 const create=[...doc.querySelectorAll('button')].find(b=>b.textContent.trim()==='Open table');assert.ok(create);await React.act(async()=>create.click());assert.equal(calls.at(-1).name,'pkTableCreate');assert.equal(calls.at(-1).args.botCount,'full');await React.act(async()=>settle.resolve({tableId:'new'}));assert.equal(created,1);
 await React.act(()=>root.unmount());w.close();console.log('PASS: spectator menu, GOD-only player identity badges, role-scoped bot controls, atomic fill request, error retry and fully populated table creation');
})().catch(async e=>{console.error(e);await React.act(()=>root.unmount());w.close();process.exitCode=1;});
