/* Server-scoped settlement screens. All amounts from the new API are cents. */
(function (global) {
'use strict';
const React=global.React;
const {useState,useEffect,useRef}=React;
const money=n=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format((Number(n)||0)/100);
const date=n=>n?new Date(n).toLocaleString('en-US',{timeZone:'Asia/Jerusalem',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
const status={open:"Open",closed:"Closed",locked:"Locked",all:"All cycles"};
function settlementError(error,fallback='Could not load settlement'){
 const message=typeof error?.message==='string'?error.message.trim():'';
 if(message&&!/[\u0590-\u05ff]/.test(message))return message;
 const code=String(error?.code||'').split('/').pop();
 return ({'permission-denied':'You do not have permission to view or change this settlement.','unauthenticated':'Please sign in again to continue.','unavailable':'The service is temporarily unavailable. Please try again.','deadline-exceeded':'The request timed out. Please try again.'})[code]||fallback;
}
function Amount({value=0,signed=false}){return <bdi className={'st-money '+(signed?(value<0?'st-loss':value>0?'st-gain':''):'')}>{signed&&value>0?'+':''}{money(value)}</bdi>;}
function Metric({label,value,note,plain=false,result,signed=false}){return <div className="st-metric"><span>{label}</span><strong>{plain?value:<Amount value={value} signed={signed}/>} {result!=null&&<span>(<Amount value={result} signed/>)</span>}</strong>{note&&<small>{note}</small>}</div>;}
function LifetimeNote({value}){return value==null?null:<small className="st-lifetime-note">Lifetime result: <Amount value={value} signed/></small>;}
function Net({value=0,kind='agent'}){
 const label=kind==='player'?(value<0?"You pay your agent / club":value>0?"Your agent / club pays you":"Settlement is balanced"):kind==='club'?(value>0?"Net amount the club receives":value<0?"Net amount the club pays":"Settlement is balanced"):(value>0?"Agent pays the club":value<0?"Club pays the agent":"Settlement is balanced");
 return <div className="st-net"><span>{label}</span><strong><Amount value={Math.abs(value)}/></strong><small>Includes opening balance and confirmed payments</small></div>;
}
function Breakdown({opening,activity,paid,kind}){return <div className="st-breakdown"><span>Opening balance <Amount value={opening} signed/></span><span>{kind==='agent'?"Club settlement this cycle":"Cycle activity"} <Amount value={activity} signed/></span><span>Net confirmed payments <Amount value={paid} signed/></span></div>;}
function TableRows({rows=[],financial=false}){return <div className="st-scroll" tabIndex="0" aria-label="Table breakdown"><table><thead><tr><th>Table / Tournament</th><th>Result</th>{financial&&<th>Rake</th>}<th>Hands</th><th>Sessions</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.tableId+'_'+i}><td>{r.tableName}<small>{r.kind==='tournament'?"Tournament":r.gameType}</small></td><td><Amount value={r.result} signed/></td>{financial&&<td><Amount value={r.rake}/></td>}<td>{r.hands}</td><td>{r.games}</td></tr>)}</tbody></table>{!rows.length&&<p className="st-empty">No completed sessions have been recorded in this cycle.</p>}</div>;}
function PaymentForm({spec,userId,clubPartyId,act,onClose,busy,error}){
 const parties=spec.type==='agent'?[spec.agentId,clubPartyId]:[spec.playerId,spec.agentId==='club'?clubPartyId:spec.agentId];
 const other=parties.find(p=>p!==userId),[direction,setDirection]=useState('out'),[amount,setAmount]=useState(''),[note,setNote]=useState('');
 return <div className="st-dialog-backdrop"><form className="st-dialog" role="dialog" aria-modal="true" aria-label="Record payment" onSubmit={async e=>{e.preventDefault();if(await act('payment',{...spec,amount:Number(amount),fromId:direction==='out'?userId:other,toId:direction==='out'?other:userId,note}))onClose();}}><h3>Record payment · {spec.name}</h3>{error&&<p role="alert" className="st-error">{error}</p>}<p>The payment is included in settlement after the other party confirms it. Your chip balance stays the same.</p><label>Direction<select value={direction} onChange={e=>setDirection(e.target.value)}><option value="out">I sent a payment</option><option value="in">I received a payment</option></select></label><label>Amount<input type="number" inputMode="decimal" min="0.01" step="0.01" required autoFocus value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Note<input maxLength="300" value={note} onChange={e=>setNote(e.target.value)}/></label><div className="st-actions"><button disabled={busy||!other||Number(amount)<=0} type="submit" className="st-primary">Send for confirmation</button><button type="button" onClick={onClose} disabled={busy}>Cancel</button></div></form></div>;
}
function Payments({items,act,busy,userId}){return <section className="st-panel"><h3>Payments and confirmations</h3>{!items.length?<p className="st-muted">No payments in the selected cycle.</p>:<div className="st-payment-list">{items.map(p=><div key={p.id} className="st-payment"><div><strong><Amount value={p.amount}/></strong><span>{p.status==='pending'?"Awaiting confirmation":p.status==='confirmed'?"Confirmed":"Cancelled"} · {date(p.at)}</span>{p.note&&<small>{p.note}</small>}</div>{p.canConfirm&&<button className="st-primary" disabled={busy} onClick={()=>act('confirmPayment',{paymentId:p.id})}>Confirm payment</button>}{p.status==='pending'&&p.createdBy===userId&&<button disabled={busy} onClick={()=>act('cancelPayment',{paymentId:p.id})}>Cancel record</button>}</div>)}</div>}</section>;}
function People({details=[],funds=[],onPay,canPay,periodLabel}){
 const [query,setQuery]=useState(''),[sort,setSort]=useState('closing'),[expanded,setExpanded]=useState('');
 const list=details.filter(p=>(p.playerName||'').toLowerCase().includes(query.toLowerCase())).map(p=>{const f=funds.find(m=>m.uid===p.playerId);return{...p,balance:f?.chips??f?.balance,totalResult:f?.totalResult};}).sort((a,b)=>sort==='name'?a.playerName.localeCompare(b.playerName):sort==='rake'?b.totals.rake-a.totals.rake:sort==='chips'?(b.balance||0)-(a.balance||0):Math.abs(b.closing)-Math.abs(a.closing));
 return <section className="st-panel"><div className="st-section-head"><h3>Player breakdown</h3><span>{details.length} settlement entries</span></div><div className="st-filters"><label className="st-search">Search players<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Player name"/></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="closing">Settlement balance</option><option value="rake">Rake — highest first</option><option value="chips">Chip balance — highest first</option><option value="name">Name</option></select></label></div><div className="st-scroll"><table><thead><tr><th>Player</th><th>Current chips (result {periodLabel})</th><th>Rake</th><th>Rakeback</th><th>Settlement balance</th><th>Actions</th></tr></thead><tbody>{list.map(p=>{const key=JSON.stringify([p.agentId,p.playerId]);return <React.Fragment key={key}><tr><td><button className="st-link" aria-expanded={expanded===key} onClick={()=>setExpanded(expanded===key?'':key)}>{p.playerName}</button></td><td>{p.balance==null?'—':<Amount value={p.balance}/>} <span>(<Amount value={p.totals.result} signed/>)</span><LifetimeNote value={p.totalResult}/></td><td><Amount value={p.totals.rake}/></td><td><Amount value={p.totals.rakeback}/></td><td><Amount value={Math.abs(p.closing)}/><small>{p.closing<0?"Player pays":p.closing>0?"Player receives":"Balanced"}</small></td><td>{canPay(p)&&<button onClick={()=>onPay({type:'player',agentId:p.agentId,playerId:p.playerId,name:p.playerName})}>Record payment</button>}</td></tr>{expanded===key&&<tr><td colSpan="6"><Breakdown opening={p.opening} activity={p.activity} paid={p.paid}/><TableRows rows={p.rows} financial/></td></tr>}</React.Fragment>;})}</tbody></table></div>{!list.length&&<p className="st-empty">No players with activity in the selected cycle.</p>}</section>;
}
function CycleControls({data,act,busy}){
 const open=data.cycles.find(c=>c.id===data.currentCycleId),[end,setEnd]=useState(''),[auto,setAuto]=useState(false);
 useEffect(()=>{if(open){const d=new Date(open.endAt);setEnd(new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16));setAuto(open.autoClose);}},[open?.id,open?.endAt,open?.autoClose]);
 return <section className="st-panel"><h3>Cycle management</h3><p className="st-muted">Closing carries the remaining settlement balance into the next cycle. Chip balances and history are preserved.</p><form className="st-filters" onSubmit={e=>{e.preventDefault();act('setEnd',{endAt:new Date(end).getTime(),autoClose:auto});}}><label>Scheduled end (local time)<input type="datetime-local" required value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="st-check"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>Close automatically</label><button disabled={busy}>Save end time</button></form><div className="st-actions"><button disabled={busy} onClick={()=>{if(global.confirm("Close this cycle and open the next one now? Chip balances will be preserved."))act('close');}}>Close cycle now</button><button disabled={busy||open?.number<=1} onClick={()=>{if(global.confirm("Reopen the previous cycle? This is only possible while the new cycle is empty."))act('reopen');}}>Reopen previous cycle</button>{data.cycle.status==='closed'&&<button disabled={busy} onClick={()=>{if(global.confirm("Lock this cycle? It cannot be reopened after locking."))act('lock',{cycleId:data.cycle.id});}}>Lock selected cycle</button>}</div></section>;
}
function Archive({call,clubId}){const [data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{let live=true;call('pkSettlementArchive',{clubId}).then(r=>live&&setData(r)).catch(e=>live&&setError(settlementError(e)));return()=>{live=false;};},[clubId]);return <section className="st-panel"><h3>Balances saved before the new cycle</h3><p className="st-muted">A snapshot of balances at the transition. Original data and game history are preserved. These amounts are not the opening balance of the new cycle.</p>{error&&<p role="alert">{error}</p>}{data?<><p>{date(data.at)}</p><div className="st-scroll"><table><thead><tr><th>Name</th><th>Saved balance</th><th>Previous cycle result</th><th>Chips including tables</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.uid}><td>{r.name}</td><td><Amount value={Math.round(r.balance*100)}/></td><td><Amount value={Math.round(r.result*100)} signed/></td><td><Amount value={Math.round(r.chips*100)}/></td></tr>)}</tbody></table></div></>:<p role="status">Loading saved balances…</p>}</section>;}
function CyclePicker({data,cycleId,setCycleId}){return <label>Cycle<select aria-label="Select cycle" value={cycleId||data.currentCycleId} onChange={e=>setCycleId(e.target.value)}>{data.cycles.map(c=><option key={c.id} value={c.id}>{c.legacy?"Cycle open before the transition":"Cycle "+c.number} · {status[c.status]}</option>)}{data.role!=='player'&&<option value="all">All cycles since the transition</option>}</select></label>;}
function LegacyCurrent({data,cycleId,setCycleId,act,busy,retry}){
 const [query,setQuery]=useState(''),[sort,setSort]=useState('chips');
 const r=data.legacyReport,t=r.totals,staff=data.role!=='player',owner=data.role==='owner',closed=data.cycle.status!=='open',periodLabel=closed?"in selected cycle":"in current cycle";
 const rows=r.players.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='result'?b.result-a.result:sort==='rake'?b.rake-a.rake:b.chips-a.chips);
 return <><header className="st-toolbar">{data.cycles.length>0&&<CyclePicker data={data} cycleId={cycleId} setCycleId={setCycleId}/>}<div className="st-period"><strong>{closed?"Previous cycle · Closed":"Current cycle · Open"}</strong><span>{date(data.cycle.startAt)} – {closed?date(data.cycle.endAt):"Now"}</span></div><button disabled={busy} onClick={retry}>Refresh</button></header><section className="st-panel"><h2>{closed?"Cycle report saved at closing":"Your current settlement"}</h2><p className="st-muted">{closed?"This report was saved when the cycle closed. Original balances and history have been preserved.":"This cycle is still open. Results include games in progress. No cycle has been closed or reset."}</p><div className="st-net"><span>{owner?"Total chips held by club players":staff?"Total chips held by my players":"My chips, including tables"}{closed?" · At closing":''}</span><strong><Amount value={t.chips}/> <span>(<Amount value={t.result} signed/>)</span></strong><small>In parentheses: profit or loss {periodLabel}. Chip top-ups are not profit.</small>{staff&&<LifetimeNote value={t.totalResult}/>}</div><div className="st-metrics"><Metric label={(staff?"Player results ":"My result ")+periodLabel} value={t.result} signed/><Metric label="Wallet chips" value={t.balance}/><Metric label="Chips at tables" value={t.onTables}/>{staff&&<><Metric label="Rake generated this cycle" value={t.rake}/><Metric label={owner?"Recorded agent commissions":"My recorded commission"} value={t.commission}/></>}</div>{staff&&<p className="st-muted">Commissions reflect amounts recorded in this cycle. Rake is already included in game results.</p>}</section>
 {owner&&<section className="st-panel"><h3>Agents {periodLabel}</h3><div className="st-scroll"><table><thead><tr><th>Agent</th><th>Chips (result {periodLabel})</th><th>Rake</th><th>Commission</th><th>Club settlement from cycle activity</th></tr></thead><tbody>{r.agents.map(a=><tr key={a.uid}><td>{a.name}</td><td><Amount value={a.chips}/> (<Amount value={a.result} signed/>)<LifetimeNote value={a.totalResult}/></td><td><Amount value={a.rake}/></td><td><Amount value={a.commission}/></td><td><Amount value={Math.abs(a.toClub)}/><small>{a.toClub>0?"Agent pays the club":a.toClub<0?"Club pays the agent":"Balanced"} · After commission</small></td></tr>)}</tbody></table></div></section>}
 {data.role==='agent'&&<section className="st-panel"><h3>Club settlement from cycle activity</h3><strong><Amount value={Math.abs(t.toClub)}/></strong><p>{t.toClub>0?"Agent pays the club":t.toClub<0?"Club pays the agent":"Balanced"} · After recorded commission</p></section>}
 {staff&&<section className="st-panel"><h3>Player breakdown</h3><div className="st-filters"><label className="st-search">Search players<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Player name"/></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="chips">Chip amount</option><option value="rake">Rake amount</option><option value="result">Cycle result</option><option value="name">Name</option></select></label></div><div className="st-scroll"><table><thead><tr><th>Player</th><th>Chips (result {periodLabel})</th><th>Cycle rake</th></tr></thead><tbody>{rows.map(p=><tr key={p.uid}><td>{p.name}</td><td><Amount value={p.chips}/> (<Amount value={p.result} signed/>)<LifetimeNote value={p.totalResult}/></td><td><Amount value={p.rake}/></td></tr>)}</tbody></table></div>{!rows.length&&<p className="st-empty">No players found.</p>}</section>}
 {data.canClose&&<section className="st-panel"><h3>Close the current cycle</h3><p>When settlement is complete, save this cycle as closed and start the next one at zero. Chip balances and history will stay the same.</p><button className="st-primary" disabled={busy} onClick={()=>{if(global.confirm("Close the current cycle and start the next one at zero? The current report will be saved for reference. Chip balances and history will stay the same. Debts and credits from this cycle will not carry over."))act('closeLegacy');}}>Close cycle and start next</button></section>}</>;
}
function Settlement({user,clubId,call,showToast=()=>{}}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[cycleId,setCycleId]=useState(''),[attempt,setAttempt]=useState(0),[busy,setBusy]=useState(false),[payment,setPayment]=useState(null),[tab,setTab]=useState('report'),[remark,setRemark]=useState('');
 const actionRef=useRef(false);
 useEffect(()=>{let live=true;setData(null);setError('');const load=()=>call('pkSettlementReport',{clubId,...(cycleId?{cycleId}:{})}).then(r=>{if(live){setData(r);setError('');}}).catch(e=>{if(live)setError(settlementError(e));});load();const timer=setInterval(load,30000);return()=>{live=false;clearInterval(timer);};},[user.uid,user.role,clubId,cycleId,attempt]);
 const act=async(action,fields={})=>{if(actionRef.current)return false;actionRef.current=true;setBusy(true);setError('');try{const result=await call('pkSettlement',{clubId,action,...fields});if(result.cycleId)setCycleId(result.cycleId);setAttempt(n=>n+1);showToast("Changes saved",'success');return true;}catch(e){setError(settlementError(e,"Could not save changes"));return false;}finally{actionRef.current=false;setBusy(false);}};
 const errorBox=error&&<div role="alert" className="st-error">{error}<button onClick={()=>setAttempt(n=>n+1)}>Try again</button></div>;
 if(!data)return <div className="settlement-app" dir="ltr">{errorBox||<p role="status">Loading your settlement…</p>}</div>;
 if(data.legacy)return <div className="settlement-app" dir="ltr">{errorBox}<LegacyCurrent data={data} cycleId={cycleId} setCycleId={setCycleId} act={act} busy={busy} retry={()=>setAttempt(n=>n+1)}/></div>;
 if(!data.active)return <div className="settlement-app" dir="ltr">{errorBox}<p role="alert">The current cycle report is unavailable. Refresh to try again.</p><button onClick={()=>setAttempt(n=>n+1)}>Refresh</button></div>;
 const owner=data.role==='owner',agent=data.role==='agent',p=data.player,a=data.agent,c=data.club?.totals,selectedCurrent=data.cycle.id===data.currentCycleId,periodLabel=data.cycle.id==='all'?"across selected cycles":selectedCurrent?"in current cycle":"in selected cycle";
 const canPay=pair=>selectedCurrent&&(pair.agentId===user.uid||pair.playerId===user.uid||pair.agentId==='club'&&data.clubPartyId===user.uid);
 return <div className="settlement-app" dir="ltr">{errorBox}<header className="st-toolbar"><CyclePicker data={data} cycleId={cycleId} setCycleId={setCycleId}/><div className="st-period"><strong>{status[data.cycle.status]}</strong><span>{date(data.cycle.startAt)} – {date(data.cycle.endAt)}</span></div><button onClick={()=>setAttempt(n=>n+1)} disabled={busy}>Refresh</button></header><nav className="st-tabs" aria-label="Settlement information"><button aria-pressed={tab==='report'} onClick={()=>setTab('report')}>Settlement report</button>{owner&&<button aria-pressed={tab==='cycles'} onClick={()=>setTab('cycles')}>Cycle management</button>}<button aria-pressed={tab==='archive'} onClick={()=>setTab('archive')}>Pre-transition balances</button></nav>{tab==='archive'?<Archive call={call} clubId={clubId}/>:tab==='cycles'&&owner?<CycleControls data={data} act={act} busy={busy}/>:<>
 <p className="st-muted st-method">Results are recorded when the session or tournament ends. Pending payments do not change the amount due.</p>
 {(owner||agent)&&data.currentTotals&&<div className="st-metrics"><Metric label={(owner?"All club players":"My players")+" · Current chips (result "+periodLabel+")"} value={data.currentTotals.chips} result={owner?c.playersResult:a.playersResult} note={data.currentTotals.totalResult!=null&&<>Lifetime result: <Amount value={data.currentTotals.totalResult} signed/></>}/></div>}
 {owner?<><Net value={c.closing} kind="club"/><div className="st-metrics"><Metric label={"Player results "+periodLabel} value={c.playersResult} signed/><Metric label="Rake generated" value={c.rake}/><Metric label="Agent commissions" value={c.commission+c.leadsIncome}/><Metric label="Hands" value={c.hands} plain/></div><section className="st-panel"><h3>Agent settlement</h3><div className="st-scroll"><table><thead><tr><th>Agent</th><th>Player results</th><th>Rake</th><th>Commission</th><th>Balance with club</th><th>Payment</th></tr></thead><tbody>{data.agents.map(x=><tr key={x.agentId}><td><details><summary>{x.agentName}</summary><Breakdown opening={x.opening} activity={x.toClub} paid={x.paid} kind="agent"/></details></td><td><Amount value={x.playersResult} signed/></td><td><Amount value={x.rake}/></td><td><Amount value={x.commission+x.leadsIncome}/></td><td><Amount value={Math.abs(x.closing)}/><small>{x.closing>0?"Agent pays the club":x.closing<0?"Club pays the agent":"Balanced"}</small></td><td>{selectedCurrent&&user.uid===data.clubPartyId&&<button onClick={()=>setPayment({type:'agent',agentId:x.agentId,name:x.agentName})}>Record payment</button>}</td></tr>)}</tbody></table></div>{!data.agents.length&&<p className="st-empty">No agent activity in this cycle.</p>}</section></>:agent?<><Net value={a.closing}/><Breakdown opening={a.opening} activity={a.toClub} paid={a.paid} kind="agent"/><div className="st-metrics"><Metric label={"My players’ results "+periodLabel} value={a.playersResult} signed/><Metric label="Rake generated" value={a.rake}/><Metric label="My commission" value={a.commission}/><Metric label="My earnings after rakeback" value={a.earnings}/></div>{selectedCurrent&&<button className="st-primary" onClick={()=>setPayment({type:'agent',agentId:user.uid,name:"Club"})}>Record payment with club</button>}{a.leads.length>0&&<section className="st-panel"><h3>Referral commissions</h3>{a.leads.map(l=><div className="st-payment" key={l.playerId}><span>{l.playerName}</span><Amount value={l.commission}/></div>)}</section>}</>:<><Net value={p.closing} kind="player"/><Breakdown opening={p.opening} activity={p.totals.result+(p.rakebackTotal||0)} paid={p.paid}/><div className="st-metrics"><Metric label={"My result "+periodLabel} value={p.totals.result} signed/><Metric label={"Current chips (result "+periodLabel+")"} value={data.chips??data.balance} result={p.totals.result}/><Metric label="Hands played" value={p.totals.hands} plain/>{p.hasRakeback&&<Metric label="My rakeback" value={p.rakebackTotal}/>}</div><section className="st-panel"><h3>My games</h3><TableRows rows={p.rows}/></section>{p.counterparties.map(x=><div className="st-payment" key={x.id}><span>{x.name==='club'?"Club":x.name} · {x.closing<0?"You pay":"You receive"} <Amount value={Math.abs(x.closing)}/></span>{selectedCurrent&&<button onClick={()=>setPayment({type:'player',agentId:x.id,playerId:user.uid,name:x.name==='club'?"Club":x.name})}>Record payment</button>}</div>)}</>}
 {(owner||agent)&&<p className="st-muted">Rake is already included in game results. The amount due to or from the club is calculated after commission; do not deduct rake again.</p>}
 {(owner||agent)&&<People details={data.details} funds={data.funds} onPay={setPayment} canPay={canPay} periodLabel={periodLabel}/>}
 <Payments items={data.payments} act={act} busy={busy} userId={user.uid}/>
 {data.cycle.id!=='all'&&data.cycle.status!=='locked'&&<section className="st-panel"><h3>Approve report or add a note</h3><label>Report note<textarea maxLength="1000" value={remark} onChange={e=>setRemark(e.target.value)} placeholder="Leave a note for the club manager"/></label><div className="st-actions"><button className="st-primary" disabled={busy} onClick={()=>act('approve',{cycleId:data.cycle.id,approved:true,remark})}>Approve report</button><button disabled={busy||!remark.trim()} onClick={()=>act('approve',{cycleId:data.cycle.id,approved:false,remark})}>Send note</button></div>{data.approvals.map(x=><p key={x.uid} className="st-muted">{x.uid===user.uid?"My approval":x.uid}: {x.approved?"Confirmed":"Note"} · {x.remark} · {date(x.at)}</p>)}</section>}
 </>}{payment&&<PaymentForm spec={payment} userId={user.uid} clubPartyId={data.clubPartyId} act={act} onClose={()=>setPayment(null)} busy={busy} error={error}/>}</div>;
}
function TermsEditor({member,agents,manager,save,busy,onClose}){
 const [draft,setDraft]=useState({primaryAgentId:member.primaryAgentId||'',secondaryAgentId:member.secondaryAgentId||'',secondaryPct:member.secondaryPct||0,rakebackPct:member.rakebackPct||0,agentType:member.agentType||'rake',agentPct:member.agentPct??member.defaultAgentPct??50});
 const field=(key,value)=>setDraft(p=>({...p,[key]:value})),isAgent=['agent','manager','club_owner'].includes(member.role);
 return <form className="st-panel st-terms-editor" onSubmit={async e=>{e.preventDefault();const patch=manager?{primaryAgentId:draft.primaryAgentId,secondaryAgentId:draft.secondaryAgentId,secondaryPct:Number(draft.secondaryPct),rakebackPct:Number(draft.rakebackPct),...(isAgent?{agentType:draft.agentType,agentPct:Number(draft.agentPct)}:{})}:{rakebackPct:Number(draft.rakebackPct)};if(await save(member.uid,patch))onClose();}}><h3>Terms · {member.name}</h3><p className="st-muted">New terms apply to sessions recorded after saving. Previous sessions keep their original terms.</p><div className="st-filters">{manager&&<><label>Primary agent<select value={draft.primaryAgentId} onChange={e=>field('primaryAgentId',e.target.value)}><option value="">Directly with club</option>{agents.filter(a=>a.uid!==member.uid).map(a=><option key={a.uid} value={a.uid}>{a.name}</option>)}</select></label><label>Secondary agent<select value={draft.secondaryAgentId} onChange={e=>field('secondaryAgentId',e.target.value)}><option value="">None</option>{agents.filter(a=>a.uid!==member.uid&&a.uid!==draft.primaryAgentId).map(a=><option key={a.uid} value={a.uid}>{a.name}</option>)}</select></label>{draft.secondaryAgentId&&<label>Referral commission (%)<input type="number" min="0" max="100" step="0.01" value={draft.secondaryPct} onChange={e=>field('secondaryPct',e.target.value)}/></label>}</>}<label>Player rakeback (%)<input type="number" min="0" max="100" step="0.01" value={draft.rakebackPct} onChange={e=>field('rakebackPct',e.target.value)}/></label>{manager&&isAgent&&<><label>Agreement type<select value={draft.agentType} onChange={e=>field('agentType',e.target.value)}><option value="rake">Percentage of rake</option><option value="result">Percentage of player results</option></select></label><label>Agent share (%)<input type="number" min="0" max="100" step="0.01" value={draft.agentPct} onChange={e=>field('agentPct',e.target.value)}/></label></>}</div><div className="st-actions"><button className="st-primary" disabled={busy}>Save terms</button><button type="button" disabled={busy} onClick={onClose}>Cancel</button></div></form>;
}
function SettlementMembers({clubId,call}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[edit,setEdit]=useState(null),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState(0);const lock=useRef(false);
 useEffect(()=>{let alive=true;call('pkSettlementTerms',{clubId,action:'list'}).then(r=>{if(alive){setData(r);setError('');}}).catch(e=>alive&&setError(settlementError(e,'Could not load member terms')));return()=>{alive=false;};},[clubId,attempt]);
 const save=async(targetUid,patch)=>{if(lock.current)return false;lock.current=true;setBusy(true);try{await call('pkSettlementTerms',{clubId,targetUid,patch});setAttempt(n=>n+1);global.dispatchEvent(new Event('pk-club-changed'));return true;}catch(e){setError(settlementError(e,'Could not save member terms'));return false;}finally{lock.current=false;setBusy(false);}};
 const agents=(data?.members||[]).filter(m=>['agent','manager','club_owner'].includes(m.role)&&m.status==='approved');
 return <section className="settlement-app" dir="ltr" id="bo-terms"><div className="st-panel"><h3>Agents and rates</h3>{error&&<div role="alert" className="st-error">{error}<button onClick={()=>setAttempt(n=>n+1)}>Try again</button></div>}{!data&&!error?<p role="status">Loading terms…</p>:data&&<><label>Search club members<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Player or agent name"/></label><div className="st-scroll"><table><thead><tr><th>Name</th><th>Primary agent</th><th>Rakeback</th><th>Edit</th></tr></thead><tbody>{data.members.filter(m=>m.status==='approved'&&m.name.toLowerCase().includes(search.toLowerCase())).map(m=><tr key={m.uid}><td>{m.name}<small>{['agent','manager','club_owner'].includes(m.role)?"Agent / Manager":"Player"}</small></td><td>{agents.find(a=>a.uid===m.primaryAgentId)?.name||"Club"}</td><td>{m.rakebackPct||0}%</td><td><button onClick={()=>setEdit(m)}>Terms</button></td></tr>)}</tbody></table></div></>}</div>{edit&&<TermsEditor key={edit.uid} member={edit} agents={agents} manager={data.role==='owner'} save={save} busy={busy} onClose={()=>setEdit(null)}/>}</section>;
}
global.PokerSettlement={Settlement,SettlementMembers,Amount,money};
})(window);
