/* Server-scoped settlement screens. All amounts from the new API are cents. */
(function (global) {
'use strict';
const React=global.React;
const {useState,useEffect,useRef}=React;
const money=n=>new Intl.NumberFormat('he-IL',{minimumFractionDigits:2,maximumFractionDigits:2}).format((Number(n)||0)/100);
const date=n=>n?new Date(n).toLocaleString('he-IL',{timeZone:'Asia/Jerusalem',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
const status={open:'פתוח',closed:'סגור',locked:'נעול',all:'כל המחזורים'};
function Amount({value=0,signed=false}){return <bdi className={'st-money '+(signed?(value<0?'st-loss':value>0?'st-gain':''):'')}>{signed&&value>0?'+':''}{money(value)}</bdi>;}
function Metric({label,value,note,plain=false,result,signed=false}){return <div className="st-metric"><span>{label}</span><strong>{plain?value:<Amount value={value} signed={signed}/>} {result!=null&&<span>(<Amount value={result} signed/>)</span>}</strong>{note&&<small>{note}</small>}</div>;}
function LifetimeNote({value}){return value==null?null:<small className="st-lifetime-note">תוצאה כללית: <Amount value={value} signed/></small>;}
function Net({value=0,kind='agent'}){
 const label=kind==='player'?(value<0?'עליך להעביר לסוכן / לקלאב':value>0?'הסוכן / הקלאב יעבירו אליך':'ההתחשבנות מאוזנת'):kind==='club'?(value>0?'הקלאב מקבל נטו':value<0?'הקלאב מעביר נטו':'ההתחשבנות מאוזנת'):(value>0?'הסוכן מעביר לקלאב':value<0?'הקלאב מעביר לסוכן':'ההתחשבנות מאוזנת');
 return <div className="st-net"><span>{label}</span><strong><Amount value={Math.abs(value)}/></strong><small>כולל יתרת פתיחה ותשלומים שאושרו</small></div>;
}
function Breakdown({opening,activity,paid,kind}){return <div className="st-breakdown"><span>יתרת פתיחה <Amount value={opening} signed/></span><span>{kind==='agent'?'מול הקלאב במחזור':'פעילות במחזור'} <Amount value={activity} signed/></span><span>תשלומים מאושרים נטו <Amount value={paid} signed/></span></div>;}
function TableRows({rows=[],financial=false}){return <div className="st-scroll" tabIndex="0" aria-label="פירוט שולחנות"><table><thead><tr><th>שולחן / טורניר</th><th>תוצאה</th>{financial&&<th>רייק</th>}<th>ידיים</th><th>סשנים</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.tableId+'_'+i}><td>{r.tableName}<small>{r.kind==='tournament'?'טורניר':r.gameType}</small></td><td><Amount value={r.result} signed/></td>{financial&&<td><Amount value={r.rake}/></td>}<td>{r.hands}</td><td>{r.games}</td></tr>)}</tbody></table>{!rows.length&&<p className="st-empty">טרם נרשמו סשנים שהסתיימו במחזור הזה.</p>}</div>;}
function PaymentForm({spec,userId,clubPartyId,act,onClose,busy,error}){
 const parties=spec.type==='agent'?[spec.agentId,clubPartyId]:[spec.playerId,spec.agentId==='club'?clubPartyId:spec.agentId];
 const other=parties.find(p=>p!==userId),[direction,setDirection]=useState('out'),[amount,setAmount]=useState(''),[note,setNote]=useState('');
 return <div className="st-dialog-backdrop"><form className="st-dialog" role="dialog" aria-modal="true" aria-label="רישום תשלום" onSubmit={async e=>{e.preventDefault();if(await act('payment',{...spec,amount:Number(amount),fromId:direction==='out'?userId:other,toId:direction==='out'?other:userId,note}))onClose();}}><h3>רישום תשלום · {spec.name}</h3>{error&&<p role="alert" className="st-error">{error}</p>}<p>התשלום ייכנס להתחשבנות לאחר אישור הצד השני. יתרת הצ׳יפים אינה משתנה.</p><label>כיוון<select value={direction} onChange={e=>setDirection(e.target.value)}><option value="out">אני העברתי</option><option value="in">קיבלתי תשלום</option></select></label><label>סכום<input type="number" inputMode="decimal" min="0.01" step="0.01" required autoFocus value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>הערה<input maxLength="300" value={note} onChange={e=>setNote(e.target.value)}/></label><div className="st-actions"><button disabled={busy||!other||Number(amount)<=0} type="submit" className="st-primary">שליחה לאישור הצד השני</button><button type="button" onClick={onClose} disabled={busy}>ביטול</button></div></form></div>;
}
function Payments({items,act,busy,userId}){return <section className="st-panel"><h3>תשלומים ואישורים</h3>{!items.length?<p className="st-muted">אין תשלומים במחזור שנבחר.</p>:<div className="st-payment-list">{items.map(p=><div key={p.id} className="st-payment"><div><strong><Amount value={p.amount}/></strong><span>{p.status==='pending'?'ממתין לאישור הצד השני':p.status==='confirmed'?'אושר':'בוטל'} · {date(p.at)}</span>{p.note&&<small>{p.note}</small>}</div>{p.canConfirm&&<button className="st-primary" disabled={busy} onClick={()=>act('confirmPayment',{paymentId:p.id})}>אישור התשלום</button>}{p.status==='pending'&&p.createdBy===userId&&<button disabled={busy} onClick={()=>act('cancelPayment',{paymentId:p.id})}>ביטול הרישום</button>}</div>)}</div>}</section>;}
function People({details=[],funds=[],onPay,canPay,periodLabel}){
 const [query,setQuery]=useState(''),[sort,setSort]=useState('closing'),[expanded,setExpanded]=useState('');
 const list=details.filter(p=>(p.playerName||'').toLowerCase().includes(query.toLowerCase())).map(p=>{const f=funds.find(m=>m.uid===p.playerId);return{...p,balance:f?.chips??f?.balance,totalResult:f?.totalResult};}).sort((a,b)=>sort==='name'?a.playerName.localeCompare(b.playerName):sort==='rake'?b.totals.rake-a.totals.rake:sort==='chips'?(b.balance||0)-(a.balance||0):Math.abs(b.closing)-Math.abs(a.closing));
 return <section className="st-panel"><div className="st-section-head"><h3>פירוט שחקנים</h3><span>{details.length} שורות התחשבנות</span></div><div className="st-filters"><label className="st-search">חיפוש שחקן<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="שם השחקן"/></label><label>סידור לפי<select value={sort} onChange={e=>setSort(e.target.value)}><option value="closing">יתרה להתחשבנות</option><option value="rake">רייק — מהגבוה לנמוך</option><option value="chips">יתרת צ׳יפים — מהגבוה לנמוך</option><option value="name">שם</option></select></label></div><div className="st-scroll"><table><thead><tr><th>שחקן</th><th>צ׳יפים כעת (תוצאה {periodLabel})</th><th>רייק</th><th>רייקבק</th><th>יתרה להתחשבנות</th><th>פעולות</th></tr></thead><tbody>{list.map(p=>{const key=JSON.stringify([p.agentId,p.playerId]);return <React.Fragment key={key}><tr><td><button className="st-link" aria-expanded={expanded===key} onClick={()=>setExpanded(expanded===key?'':key)}>{p.playerName}</button></td><td>{p.balance==null?'—':<Amount value={p.balance}/>} <span>(<Amount value={p.totals.result} signed/>)</span><LifetimeNote value={p.totalResult}/></td><td><Amount value={p.totals.rake}/></td><td><Amount value={p.totals.rakeback}/></td><td><Amount value={Math.abs(p.closing)}/><small>{p.closing<0?'השחקן מעביר':p.closing>0?'השחקן מקבל':'מאוזן'}</small></td><td>{canPay(p)&&<button onClick={()=>onPay({type:'player',agentId:p.agentId,playerId:p.playerId,name:p.playerName})}>רישום תשלום</button>}</td></tr>{expanded===key&&<tr><td colSpan="6"><Breakdown opening={p.opening} activity={p.activity} paid={p.paid}/><TableRows rows={p.rows} financial/></td></tr>}</React.Fragment>;})}</tbody></table></div>{!list.length&&<p className="st-empty">לא נמצאו שחקנים עם פעילות במחזור שנבחר.</p>}</section>;
}
function CycleControls({data,act,busy}){
 const open=data.cycles.find(c=>c.id===data.currentCycleId),[end,setEnd]=useState(''),[auto,setAuto]=useState(false);
 useEffect(()=>{if(open){const d=new Date(open.endAt);setEnd(new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16));setAuto(open.autoClose);}},[open?.id,open?.endAt,open?.autoClose]);
 return <section className="st-panel"><h3>ניהול מחזורים</h3><p className="st-muted">סגירה מעבירה את היתרה שנותרה למחזור הבא. היא אינה מאפסת צ׳יפים או מוחקת היסטוריה.</p><form className="st-filters" onSubmit={e=>{e.preventDefault();act('setEnd',{endAt:new Date(end).getTime(),autoClose:auto});}}><label>סיום מתוכנן (השעה המקומית)<input type="datetime-local" required value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="st-check"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>סגירה אוטומטית</label><button disabled={busy}>שמירת מועד הסיום</button></form><div className="st-actions"><button disabled={busy} onClick={()=>{if(global.confirm('לסגור כעת את המחזור ולפתוח את הבא? יתרות הצ׳יפים יישמרו.'))act('close');}}>סגירת המחזור כעת</button><button disabled={busy||open?.number<=1} onClick={()=>{if(global.confirm('לפתוח מחדש את המחזור הקודם? הפעולה אפשרית רק כשהמחזור החדש ריק.'))act('reopen');}}>פתיחת המחזור הקודם מחדש</button>{data.cycle.status==='closed'&&<button disabled={busy} onClick={()=>{if(global.confirm('לנעול את המחזור הזה? לא ניתן יהיה לפתוח אותו מחדש.'))act('lock',{cycleId:data.cycle.id});}}>נעילת המחזור שנבחר</button>}</div></section>;
}
function Archive({call,clubId}){const [data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{let live=true;call('pkSettlementArchive',{clubId}).then(r=>live&&setData(r)).catch(e=>live&&setError(e.message));return()=>{live=false;};},[clubId]);return <section className="st-panel"><h3>המצב שנשמר לפני תחילת המחזור החדש</h3><p className="st-muted">צילום הסכומים בזמן המעבר. הנתונים המקוריים והיסטוריית המשחקים נשמרים. סכומים אלה אינם יתרת פתיחה במחזור החדש.</p>{error&&<p role="alert">{error}</p>}{data?<><p>{date(data.at)}</p><div className="st-scroll"><table><thead><tr><th>שם</th><th>יתרה שנשמרה</th><th>תוצאת המחזור הקודם</th><th>צ׳יפים כולל שולחנות</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.uid}><td>{r.name}</td><td><Amount value={Math.round(r.balance*100)}/></td><td><Amount value={Math.round(r.result*100)} signed/></td><td><Amount value={Math.round(r.chips*100)}/></td></tr>)}</tbody></table></div></>:<p role="status">טוען סכומים שמורים…</p>}</section>;}
function CyclePicker({data,cycleId,setCycleId}){return <label>מחזור<select aria-label="בחירת מחזור" value={cycleId||data.currentCycleId} onChange={e=>setCycleId(e.target.value)}>{data.cycles.map(c=><option key={c.id} value={c.id}>{c.legacy?'המחזור שהיה פתוח לפני המעבר':'מחזור '+c.number} · {status[c.status]}</option>)}{data.role!=='player'&&<option value="all">כל המחזורים מאז המעבר</option>}</select></label>;}
function LegacyCurrent({data,cycleId,setCycleId,act,busy,retry}){
 const [query,setQuery]=useState(''),[sort,setSort]=useState('chips');
 const r=data.legacyReport,t=r.totals,staff=data.role!=='player',owner=data.role==='owner',closed=data.cycle.status!=='open',periodLabel=closed?'במחזור שנבחר':'במחזור הנוכחי';
 const rows=r.players.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='result'?b.result-a.result:sort==='rake'?b.rake-a.rake:b.chips-a.chips);
 return <><header className="st-toolbar">{data.cycles.length>0&&<CyclePicker data={data} cycleId={cycleId} setCycleId={setCycleId}/>}<div className="st-period"><strong>{closed?'המחזור הקודם · סגור':'המחזור הנוכחי · פתוח'}</strong><span>{date(data.cycle.startAt)} – {closed?date(data.cycle.endAt):'עד עכשיו'}</span></div><button disabled={busy} onClick={retry}>רענון</button></header><section className="st-panel"><h2>{closed?'דוח המחזור שנשמר בסגירה':'ההתחשבנות הנוכחית שלך'}</h2><p className="st-muted">{closed?'זהו הדוח שנשמר בזמן הסגירה. היתרות וההיסטוריה המקוריות נשמרו.':'המחזור עדיין פתוח. מוצגות התוצאות הקיימות, כולל משחקים שעדיין מתנהלים. שום מחזור לא נסגר ולא אופס.'}</p><div className="st-net"><span>{owner?'סך הצ׳יפים של שחקני הקלאב':staff?'סך הצ׳יפים של השחקנים שלי':'הצ׳יפים שלי, כולל שולחנות'}{closed?' · בזמן הסגירה':''}</span><strong><Amount value={t.chips}/> <span>(<Amount value={t.result} signed/>)</span></strong><small>בסוגריים: הרווח או ההפסד {periodLabel}. טעינות צ׳יפים אינן רווח.</small>{staff&&<LifetimeNote value={t.totalResult}/>}</div><div className="st-metrics"><Metric label={(staff?'תוצאות השחקנים ':'התוצאה שלי ')+periodLabel} value={t.result} signed/><Metric label="צ׳יפים בארנק" value={t.balance}/><Metric label="צ׳יפים בשולחנות" value={t.onTables}/>{staff&&<><Metric label="רייק שנוצר במחזור" value={t.rake}/><Metric label={owner?'עמלות הסוכנים שנרשמו':'העמלה שלי שנרשמה'} value={t.commission}/></>}</div>{staff&&<p className="st-muted">עמלות מוצגות לפי מה שנרשם בפועל במחזור. הרייק כבר מגולם בתוצאות המשחק.</p>}</section>
 {owner&&<section className="st-panel"><h3>הסוכנים {periodLabel}</h3><div className="st-scroll"><table><thead><tr><th>סוכן</th><th>צ׳יפים (תוצאה {periodLabel})</th><th>רייק</th><th>עמלה</th><th>מול הקלאב לפי פעילות המחזור</th></tr></thead><tbody>{r.agents.map(a=><tr key={a.uid}><td>{a.name}</td><td><Amount value={a.chips}/> (<Amount value={a.result} signed/>)<LifetimeNote value={a.totalResult}/></td><td><Amount value={a.rake}/></td><td><Amount value={a.commission}/></td><td><Amount value={Math.abs(a.toClub)}/><small>{a.toClub>0?'הסוכן מעביר לקלאב':a.toClub<0?'הקלאב מעביר לסוכן':'מאוזן'} · לאחר העמלה</small></td></tr>)}</tbody></table></div></section>}
 {data.role==='agent'&&<section className="st-panel"><h3>מול הקלאב לפי פעילות המחזור</h3><strong><Amount value={Math.abs(t.toClub)}/></strong><p>{t.toClub>0?'הסוכן מעביר לקלאב':t.toClub<0?'הקלאב מעביר לסוכן':'מאוזן'} · לאחר העמלה שנרשמה</p></section>}
 {staff&&<section className="st-panel"><h3>פירוט השחקנים</h3><div className="st-filters"><label className="st-search">חיפוש שחקן<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="שם השחקן"/></label><label>סידור לפי<select value={sort} onChange={e=>setSort(e.target.value)}><option value="chips">כמות צ׳יפים</option><option value="rake">גובה רייק</option><option value="result">תוצאה במחזור</option><option value="name">שם</option></select></label></div><div className="st-scroll"><table><thead><tr><th>שחקן</th><th>צ׳יפים (תוצאה {periodLabel})</th><th>רייק במחזור</th></tr></thead><tbody>{rows.map(p=><tr key={p.uid}><td>{p.name}</td><td><Amount value={p.chips}/> (<Amount value={p.result} signed/>)<LifetimeNote value={p.totalResult}/></td><td><Amount value={p.rake}/></td></tr>)}</tbody></table></div>{!rows.length&&<p className="st-empty">לא נמצאו שחקנים.</p>}</section>}
 {data.canClose&&<section className="st-panel"><h3>סיום המחזור הנוכחי</h3><p>רק כשתסיים את ההתחשבנות: שמירת המחזור הנוכחי כסגור ופתיחת המחזור הבא באפס. יתרות הצ׳יפים וההיסטוריה יישארו כפי שהן.</p><button className="st-primary" disabled={busy} onClick={()=>{if(global.confirm('לסגור את המחזור הנוכחי ולפתוח את הבא באפס? הדוח הנוכחי יישמר לעיון. יתרות הצ׳יפים וההיסטוריה לא ישתנו, וחובות או זיכויים מהמחזור הנוכחי לא יועברו למחזור הבא.'))act('closeLegacy');}}>סגירת המחזור ופתיחת הבא</button></section>}</>;
}
function Settlement({user,clubId,call,showToast=()=>{}}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[cycleId,setCycleId]=useState(''),[attempt,setAttempt]=useState(0),[busy,setBusy]=useState(false),[payment,setPayment]=useState(null),[tab,setTab]=useState('report'),[remark,setRemark]=useState('');
 const actionRef=useRef(false);
 useEffect(()=>{let live=true;setData(null);setError('');const load=()=>call('pkSettlementReport',{clubId,...(cycleId?{cycleId}:{})}).then(r=>{if(live){setData(r);setError('');}}).catch(e=>{if(live)setError(e.message||'טעינת ההתחשבנות נכשלה');});load();const timer=setInterval(load,30000);return()=>{live=false;clearInterval(timer);};},[user.uid,user.role,clubId,cycleId,attempt]);
 const act=async(action,fields={})=>{if(actionRef.current)return false;actionRef.current=true;setBusy(true);setError('');try{const result=await call('pkSettlement',{clubId,action,...fields});if(result.cycleId)setCycleId(result.cycleId);setAttempt(n=>n+1);showToast('הפעולה נשמרה','success');return true;}catch(e){setError(e.message||'הפעולה לא נשמרה');return false;}finally{actionRef.current=false;setBusy(false);}};
 const errorBox=error&&<div role="alert" className="st-error">{error}<button onClick={()=>setAttempt(n=>n+1)}>נסה שוב</button></div>;
 if(!data)return <div className="settlement-app" dir="rtl">{errorBox||<p role="status">טוען את ההתחשבנות שלך…</p>}</div>;
 if(data.legacy)return <div className="settlement-app" dir="rtl">{errorBox}<LegacyCurrent data={data} cycleId={cycleId} setCycleId={setCycleId} act={act} busy={busy} retry={()=>setAttempt(n=>n+1)}/></div>;
 if(!data.active)return <div className="settlement-app" dir="rtl">{errorBox}<p role="alert">לא התקבל דוח המחזור הנוכחי. יש לרענן כדי לנסות שוב.</p><button onClick={()=>setAttempt(n=>n+1)}>רענון</button></div>;
 const owner=data.role==='owner',agent=data.role==='agent',p=data.player,a=data.agent,c=data.club?.totals,selectedCurrent=data.cycle.id===data.currentCycleId,periodLabel=data.cycle.id==='all'?'בכל המחזורים שנבחרו':selectedCurrent?'במחזור הנוכחי':'במחזור שנבחר';
 const canPay=pair=>selectedCurrent&&(pair.agentId===user.uid||pair.playerId===user.uid||pair.agentId==='club'&&data.clubPartyId===user.uid);
 return <div className="settlement-app" dir="rtl">{errorBox}<header className="st-toolbar"><CyclePicker data={data} cycleId={cycleId} setCycleId={setCycleId}/><div className="st-period"><strong>{status[data.cycle.status]}</strong><span>{date(data.cycle.startAt)} – {date(data.cycle.endAt)}</span></div><button onClick={()=>setAttempt(n=>n+1)} disabled={busy}>רענון</button></header><nav className="st-tabs" aria-label="מידע והתחשבנות"><button aria-pressed={tab==='report'} onClick={()=>setTab('report')}>דוח התחשבנות</button>{owner&&<button aria-pressed={tab==='cycles'} onClick={()=>setTab('cycles')}>ניהול מחזורים</button>}<button aria-pressed={tab==='archive'} onClick={()=>setTab('archive')}>סכומים לפני המעבר</button></nav>{tab==='archive'?<Archive call={call} clubId={clubId}/>:tab==='cycles'&&owner?<CycleControls data={data} act={act} busy={busy}/>:<>
 <p className="st-muted st-method">התוצאות נרשמות בסיום הסשן או הטורניר. תשלום ממתין אינו משנה את הסכום לתשלום.</p>
 {(owner||agent)&&data.currentTotals&&<div className="st-metrics"><Metric label={(owner?"כל שחקני הקלאב":"השחקנים שלי")+" · צ׳יפים כעת (תוצאה "+periodLabel+")"} value={data.currentTotals.chips} result={owner?c.playersResult:a.playersResult} note={data.currentTotals.totalResult!=null&&<>תוצאה כללית: <Amount value={data.currentTotals.totalResult} signed/></>}/></div>}
 {owner?<><Net value={c.closing} kind="club"/><div className="st-metrics"><Metric label={"תוצאות השחקנים "+periodLabel} value={c.playersResult} signed/><Metric label="רייק שנוצר" value={c.rake}/><Metric label="עמלות סוכנים" value={c.commission+c.leadsIncome}/><Metric label="ידיים" value={c.hands} plain/></div><section className="st-panel"><h3>התחשבנות מול הסוכנים</h3><div className="st-scroll"><table><thead><tr><th>סוכן</th><th>תוצאות שחקנים</th><th>רייק</th><th>עמלה</th><th>יתרה מול הקלאב</th><th>תשלום</th></tr></thead><tbody>{data.agents.map(x=><tr key={x.agentId}><td><details><summary>{x.agentName}</summary><Breakdown opening={x.opening} activity={x.toClub} paid={x.paid} kind="agent"/></details></td><td><Amount value={x.playersResult} signed/></td><td><Amount value={x.rake}/></td><td><Amount value={x.commission+x.leadsIncome}/></td><td><Amount value={Math.abs(x.closing)}/><small>{x.closing>0?'הסוכן מעביר לקלאב':x.closing<0?'הקלאב מעביר לסוכן':'מאוזן'}</small></td><td>{selectedCurrent&&user.uid===data.clubPartyId&&<button onClick={()=>setPayment({type:'agent',agentId:x.agentId,name:x.agentName})}>רישום תשלום</button>}</td></tr>)}</tbody></table></div>{!data.agents.length&&<p className="st-empty">אין פעילות סוכנים במחזור הזה.</p>}</section></>:agent?<><Net value={a.closing}/><Breakdown opening={a.opening} activity={a.toClub} paid={a.paid} kind="agent"/><div className="st-metrics"><Metric label={"תוצאות השחקנים שלי "+periodLabel} value={a.playersResult} signed/><Metric label="רייק שנוצר" value={a.rake}/><Metric label="העמלה שלי" value={a.commission}/><Metric label="נשאר לי לאחר רייקבק" value={a.earnings}/></div>{selectedCurrent&&<button className="st-primary" onClick={()=>setPayment({type:'agent',agentId:user.uid,name:'הקלאב'})}>רישום תשלום מול הקלאב</button>}{a.leads.length>0&&<section className="st-panel"><h3>עמלות הפניה</h3>{a.leads.map(l=><div className="st-payment" key={l.playerId}><span>{l.playerName}</span><Amount value={l.commission}/></div>)}</section>}</>:<><Net value={p.closing} kind="player"/><Breakdown opening={p.opening} activity={p.totals.result+(p.rakebackTotal||0)} paid={p.paid}/><div className="st-metrics"><Metric label={"התוצאה שלי "+periodLabel} value={p.totals.result} signed/><Metric label={"צ׳יפים כעת (תוצאה "+periodLabel+")"} value={data.chips??data.balance} result={p.totals.result}/><Metric label="ידיים ששיחקתי" value={p.totals.hands} plain/>{p.hasRakeback&&<Metric label="הרייקבק שלי" value={p.rakebackTotal}/>}</div><section className="st-panel"><h3>המשחקים שלי</h3><TableRows rows={p.rows}/></section>{p.counterparties.map(x=><div className="st-payment" key={x.id}><span>{x.name==='club'?'הקלאב':x.name} · {x.closing<0?'עליך להעביר':'עליך לקבל'} <Amount value={Math.abs(x.closing)}/></span>{selectedCurrent&&<button onClick={()=>setPayment({type:'player',agentId:x.id,playerId:user.uid,name:x.name==='club'?'הקלאב':x.name})}>רישום תשלום</button>}</div>)}</>}
 {(owner||agent)&&<p className="st-muted">הרייק כבר מגולם בתוצאות המשחק. הסכום מול הקלאב מחושב לאחר קיזוז העמלה; אין להפחית את הרייק שוב.</p>}
 {(owner||agent)&&<People details={data.details} funds={data.funds} onPay={setPayment} canPay={canPay} periodLabel={periodLabel}/>}
 <Payments items={data.payments} act={act} busy={busy} userId={user.uid}/>
 {data.cycle.id!=='all'&&data.cycle.status!=='locked'&&<section className="st-panel"><h3>אישור הדוח או הערה</h3><label>הערה לדוח<textarea maxLength="1000" value={remark} onChange={e=>setRemark(e.target.value)} placeholder="אפשר להשאיר הערה למנהל הקלאב"/></label><div className="st-actions"><button className="st-primary" disabled={busy} onClick={()=>act('approve',{cycleId:data.cycle.id,approved:true,remark})}>הדוח מאושר מבחינתי</button><button disabled={busy||!remark.trim()} onClick={()=>act('approve',{cycleId:data.cycle.id,approved:false,remark})}>שליחת הערה</button></div>{data.approvals.map(x=><p key={x.uid} className="st-muted">{x.uid===user.uid?'האישור שלי':x.uid}: {x.approved?'אושר':'הערה'} · {x.remark} · {date(x.at)}</p>)}</section>}
 </>}{payment&&<PaymentForm spec={payment} userId={user.uid} clubPartyId={data.clubPartyId} act={act} onClose={()=>setPayment(null)} busy={busy} error={error}/>}</div>;
}
function TermsEditor({member,agents,manager,save,busy,onClose}){
 const [draft,setDraft]=useState({primaryAgentId:member.primaryAgentId||'',secondaryAgentId:member.secondaryAgentId||'',secondaryPct:member.secondaryPct||0,rakebackPct:member.rakebackPct||0,agentType:member.agentType||'rake',agentPct:member.agentPct??member.defaultAgentPct??50});
 const field=(key,value)=>setDraft(p=>({...p,[key]:value})),isAgent=['agent','manager','club_owner'].includes(member.role);
 return <form className="st-panel st-terms-editor" onSubmit={async e=>{e.preventDefault();const patch=manager?{primaryAgentId:draft.primaryAgentId,secondaryAgentId:draft.secondaryAgentId,secondaryPct:Number(draft.secondaryPct),rakebackPct:Number(draft.rakebackPct),...(isAgent?{agentType:draft.agentType,agentPct:Number(draft.agentPct)}:{})}:{rakebackPct:Number(draft.rakebackPct)};if(await save(member.uid,patch))onClose();}}><h3>תנאים · {member.name}</h3><p className="st-muted">התנאים החדשים יחולו על סשנים שיירשמו לאחר השמירה. סשנים קודמים נשארים לפי התנאים המקוריים.</p><div className="st-filters">{manager&&<><label>סוכן אחראי<select value={draft.primaryAgentId} onChange={e=>field('primaryAgentId',e.target.value)}><option value="">ישירות מול הקלאב</option>{agents.filter(a=>a.uid!==member.uid).map(a=><option key={a.uid} value={a.uid}>{a.name}</option>)}</select></label><label>סוכן משני<select value={draft.secondaryAgentId} onChange={e=>field('secondaryAgentId',e.target.value)}><option value="">ללא</option>{agents.filter(a=>a.uid!==member.uid&&a.uid!==draft.primaryAgentId).map(a=><option key={a.uid} value={a.uid}>{a.name}</option>)}</select></label>{draft.secondaryAgentId&&<label>עמלת הפניה (%)<input type="number" min="0" max="100" step="0.01" value={draft.secondaryPct} onChange={e=>field('secondaryPct',e.target.value)}/></label>}</>}<label>רייקבק לשחקן (%)<input type="number" min="0" max="100" step="0.01" value={draft.rakebackPct} onChange={e=>field('rakebackPct',e.target.value)}/></label>{manager&&isAgent&&<><label>סוג הסכם<select value={draft.agentType} onChange={e=>field('agentType',e.target.value)}><option value="rake">אחוז מהרייק</option><option value="result">אחוז מתוצאות השחקנים</option></select></label><label>חלק הסוכן (%)<input type="number" min="0" max="100" step="0.01" value={draft.agentPct} onChange={e=>field('agentPct',e.target.value)}/></label></>}</div><div className="st-actions"><button className="st-primary" disabled={busy}>שמירת התנאים</button><button type="button" disabled={busy} onClick={onClose}>ביטול</button></div></form>;
}
function SettlementMembers({clubId,call}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[edit,setEdit]=useState(null),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState(0);const lock=useRef(false);
 useEffect(()=>{let alive=true;call('pkSettlementTerms',{clubId,action:'list'}).then(r=>{if(alive){setData(r);setError('');}}).catch(e=>alive&&setError(e.message));return()=>{alive=false;};},[clubId,attempt]);
 const save=async(targetUid,patch)=>{if(lock.current)return false;lock.current=true;setBusy(true);try{await call('pkSettlementTerms',{clubId,targetUid,patch});setAttempt(n=>n+1);global.dispatchEvent(new Event('pk-club-changed'));return true;}catch(e){setError(e.message);return false;}finally{lock.current=false;setBusy(false);}};
 const agents=(data?.members||[]).filter(m=>['agent','manager','club_owner'].includes(m.role)&&m.status==='approved');
 return <section className="settlement-app" dir="rtl" id="bo-terms"><div className="st-panel"><h3>סוכנים ואחוזים</h3>{error&&<div role="alert" className="st-error">{error}<button onClick={()=>setAttempt(n=>n+1)}>נסה שוב</button></div>}{!data&&!error?<p role="status">טוען תנאים…</p>:data&&<><label>חיפוש חבר קלאב<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="שם השחקן או הסוכן"/></label><div className="st-scroll"><table><thead><tr><th>שם</th><th>סוכן אחראי</th><th>רייקבק</th><th>עריכה</th></tr></thead><tbody>{data.members.filter(m=>m.status==='approved'&&m.name.toLowerCase().includes(search.toLowerCase())).map(m=><tr key={m.uid}><td>{m.name}<small>{['agent','manager','club_owner'].includes(m.role)?'סוכן / מנהל':'שחקן'}</small></td><td>{agents.find(a=>a.uid===m.primaryAgentId)?.name||'הקלאב'}</td><td>{m.rakebackPct||0}%</td><td><button onClick={()=>setEdit(m)}>תנאים</button></td></tr>)}</tbody></table></div></>}</div>{edit&&<TermsEditor key={edit.uid} member={edit} agents={agents} manager={data.role==='owner'} save={save} busy={busy} onClose={()=>setEdit(null)}/>}</section>;
}
global.PokerSettlement={Settlement,SettlementMembers,Amount,money};
})(window);
