/* Server-scoped settlement screens. All amounts from the new API are cents. */
(function (global) {
'use strict';
const React=global.React;
const {useState,useEffect,useRef}=React;
const money=n=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format((Number(n)||0)/100);
const CLUB_TIME_ZONE='Asia/Jerusalem';
const date=n=>n?new Date(n).toLocaleString('en-US',{timeZone:CLUB_TIME_ZONE,day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
const status={open:"Open",closed:"Closed",locked:"Locked",all:"All cycles",range:"Date range · Read only"};
const clubClock=new Intl.DateTimeFormat('en-GB',{timeZone:CLUB_TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});
const clubParts=epoch=>Object.fromEntries(clubClock.formatToParts(new Date(epoch)).filter(p=>p.type!=='literal').map(p=>[p.type,Number(p.value)]));
const clubWall=epoch=>{const p=clubParts(epoch);return Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second);};
// Resolve calendar inputs in the same club timezone as report timestamps.
// Checking both sides of a transition rejects nonexistent and repeated wall times.
function clubEpoch(target){
 const offsets=new Set([-36,0,36].map(hours=>{const epoch=target+hours*3600000;return clubWall(epoch)-epoch;}));
 const matches=[...offsets].map(offset=>target-offset).filter(epoch=>clubWall(epoch)===target);
 return matches.length===1?matches[0]:null;
}
function clubDayStart(value,nextDay=false){
 if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return null;
 const [year,month,day]=value.split('-').map(Number),check=new Date(Date.UTC(year,month-1,day));
 if(check.getUTCFullYear()!==year||check.getUTCMonth()!==month-1||check.getUTCDate()!==day)return null;
 return clubEpoch(Date.UTC(year,month-1,day+(nextDay?1:0)));
}
function clubDateTime(value){
 if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value||''))return null;
 const [day,time]=value.split('T'),[year,month,date]=day.split('-').map(Number),[hour,minute]=time.split(':').map(Number),target=Date.UTC(year,month-1,date,hour,minute),check=new Date(target);
 if(check.getUTCFullYear()!==year||check.getUTCMonth()!==month-1||check.getUTCDate()!==date||hour>23||minute>59)return null;
 return clubEpoch(target);
}
const clubDay=n=>{if(!Number.isFinite(n))return '';const p=clubParts(n);return `${p.year}-${String(p.month).padStart(2,'0')}-${String(p.day).padStart(2,'0')}`;};
const rangeDates=r=>`${new Date(r.fromAt).toLocaleDateString('en-US',{timeZone:CLUB_TIME_ZONE})} – ${new Date(r.toAt-1).toLocaleDateString('en-US',{timeZone:CLUB_TIME_ZONE})}`;
function settlementError(error,fallback='Could not load settlement'){
 const message=typeof error?.message==='string'?error.message.trim():'';
 if(message&&!/[\u0590-\u05ff]/.test(message))return message;
 const code=String(error?.code||'').split('/').pop();
 return ({'permission-denied':'You do not have permission to view or change this settlement.','unauthenticated':'Please sign in again to continue.','unavailable':'The service is temporarily unavailable. Please try again.','deadline-exceeded':'The request timed out. Please try again.'})[code]||fallback;
}
function Amount({value=0,signed=false}){return <bdi className={'st-money '+(signed?(value<0?'st-loss':value>0?'st-gain':''):'')}>{signed&&value>0?'+':''}{money(value)}</bdi>;}
function Metric({label,value,note,plain=false,signed=false}){return <div className="st-metric"><span>{label}</span><strong>{plain?value:<Amount value={value} signed={signed}/>}</strong>{note&&<small>{note}</small>}</div>;}
function LifetimeNote({value}){return <small className="st-lifetime-note"><span>Lifetime profit/loss</span>{value==null?<span>Unavailable</span>:<Amount value={value} signed/>}</small>;}
function FundsResult({chips,result,totalResult,canSeeLifetime=false,periodLabel='in current cycle',balanceLabel='Current balance'}){
 const resultLabel=periodLabel==='in selected dates'?'Recorded profit/loss':periodLabel==='in selected cycle'?'Selected cycle profit/loss':periodLabel==='across selected cycles'?'Selected cycles profit/loss':'Cycle profit/loss';
 return <div className="st-funds-result"><div className="st-balance-line"><span>{balanceLabel}</span><strong>{chips==null?'Unavailable':<Amount value={chips}/>}</strong></div><div className="st-cycle-line"><span>{resultLabel}</span><strong>{result==null?'Awaiting cycle start':<Amount value={result} signed/>}</strong></div>{canSeeLifetime&&<LifetimeNote value={totalResult}/>}</div>;
}
function ReportDates({data,range,onRange,onCurrent,busy}){
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[error,setError]=useState('');
 useEffect(()=>{if(range){setFrom(clubDay(range.fromAt));setTo(clubDay(range.toAt-1));}},[range?.fromAt,range?.toAt]);
 if(!data.supportsDateRange)return null;
 return <details className="st-panel" open={!!range}><summary style={{minHeight:44,cursor:'pointer',fontWeight:750}}>Report dates · View history</summary><p className="st-muted">The current cycle stays open until a manager closes it manually. Viewing history does not reset the cycle or change balances.</p><form className="st-filters" aria-label="Report date range" onSubmit={e=>{e.preventDefault();const fromAt=clubDayStart(from),toAt=clubDayStart(to,true);if(!Number.isFinite(fromAt)||!Number.isFinite(toAt)||fromAt>=toAt){setError('Choose a valid start and end date. The end date must be on or after the start date.');return;}setError('');onRange({fromAt,toAt});}}><label>From date<input type="date" required value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To date (inclusive)<input type="date" required value={to} onChange={e=>setTo(e.target.value)}/></label><button disabled={busy} className="st-primary">View date range</button></form>{error&&<p role="alert" className="st-error">{error}</p>}<p className="st-muted">All dates use club time (Asia/Jerusalem). Both selected dates are included. Historical reports use cash-outs and completed tournaments recorded within the selected dates. Chips shown are the current balance.</p>{range&&<div className="st-actions"><strong>Date range · Read only · {rangeDates(range)}</strong><button disabled={busy} onClick={onCurrent}>Back to current cycle</button></div>}</details>;
}
function PeriodStartRequired({data,act,busy}){
 const [start,setStart]=useState(''),[error,setError]=useState('');
 const t=data.legacyReport?.totals,owner=data.role==='owner';
 return <section className="st-panel"><h2>Current cycle start is required</h2><p role="status">The current cycle has no confirmed start date. Its result is unavailable until a manager selects the correct date.</p><p className="st-muted">Balances and game history are preserved. Setting the start date does not close a cycle or change anyone’s chips. The confirmed start stays fixed until the cycle is closed manually.</p><FundsResult chips={t?.chips} result={null} totalResult={t?.totalResult} canSeeLifetime={owner}/><p className="st-muted">Chip balances are funds held, not profit or loss.</p>{data.canSetPeriodStart?<form className="st-filters" aria-label="Set current cycle start" onSubmit={async e=>{e.preventDefault();const startAt=clubDateTime(start);if(!Number.isFinite(startAt)){setError('Choose a valid, unambiguous club time. Times skipped or repeated by daylight saving cannot be used.');return;}if(startAt>Date.now()){setError('Choose the confirmed cycle start date and time. It cannot be in the future.');return;}setError('');await act('setLegacyPeriodStart',{startAt});}}><label>Current cycle start · Club time (Asia/Jerusalem)<input type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></label><button disabled={busy||!start} className="st-primary">Save cycle start</button>{error&&<p role="alert" className="st-error">{error}</p>}</form>:<p>Please ask your club manager to confirm the cycle start date.</p>}</section>;
}
function Net({value=0,kind='agent'}){
 const label=kind==='player'?(value<0?"You pay your agent / club":value>0?"Your agent / club pays you":"Settlement is balanced"):kind==='club'?(value>0?"Net amount the club receives":value<0?"Net amount the club pays":"Settlement is balanced"):(value>0?"Agent pays the club":value<0?"Club pays the agent":"Settlement is balanced");
 return <div className="st-net"><span>{label}</span><strong><Amount value={Math.abs(value)}/></strong><small>Includes opening balance and confirmed payments</small></div>;
}
function Breakdown({opening,activity,paid,kind}){return <div className="st-breakdown"><span>Opening balance <Amount value={opening} signed/></span><span>{kind==='agent'?"Club settlement this cycle":"Cycle activity"} <Amount value={activity} signed/></span><span>Net confirmed payments <Amount value={paid} signed/></span></div>;}
function TableRows({rows=[],financial=false}){return <div className="st-scroll" tabIndex="0" aria-label="Table breakdown"><table><thead><tr><th>Table / Tournament</th><th>Result</th>{financial&&<th>Rake</th>}<th>Hands</th><th>Sessions</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.tableId+'_'+i}><td>{r.tableName}<small>{r.kind==='tournament'?"Tournament":r.gameType}</small></td><td><Amount value={r.result} signed/></td>{financial&&<td><Amount value={r.rake}/></td>}<td>{r.hands}</td><td>{r.games}</td></tr>)}</tbody></table>{!rows.length&&<p className="st-empty">No activity has been recorded in this cycle.</p>}</div>;}
function PaymentForm({spec,userId,clubPartyId,act,onClose,busy,error}){
 const parties=spec.type==='agent'?[spec.agentId,clubPartyId]:[spec.playerId,spec.agentId==='club'?clubPartyId:spec.agentId];
 const other=parties.find(p=>p!==userId),[direction,setDirection]=useState('out'),[amount,setAmount]=useState(''),[note,setNote]=useState('');
 return <div className="st-dialog-backdrop"><form className="st-dialog" role="dialog" aria-modal="true" aria-label="Record payment" onSubmit={async e=>{e.preventDefault();if(await act('payment',{...spec,amount:Number(amount),fromId:direction==='out'?userId:other,toId:direction==='out'?other:userId,note}))onClose();}}><h3>Record payment · {spec.name}</h3>{error&&<p role="alert" className="st-error">{error}</p>}<p>The payment is included in settlement after the other party confirms it. Your chip balance stays the same.</p><label>Direction<select value={direction} onChange={e=>setDirection(e.target.value)}><option value="out">I sent a payment</option><option value="in">I received a payment</option></select></label><label>Amount<input type="number" inputMode="decimal" min="0.01" step="0.01" required autoFocus value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Note<input maxLength="300" value={note} onChange={e=>setNote(e.target.value)}/></label><div className="st-actions"><button disabled={busy||!other||Number(amount)<=0} type="submit" className="st-primary">Send for confirmation</button><button type="button" onClick={onClose} disabled={busy}>Cancel</button></div></form></div>;
}
function Payments({items,act,busy,userId,readOnly=false}){return <section className="st-panel"><h3>Payments and confirmations</h3>{!items.length?<p className="st-muted">No payments in the selected cycle.</p>:<div className="st-payment-list">{items.map(p=><div key={p.id} className="st-payment"><div><strong><Amount value={p.amount}/></strong><span>{p.status==='pending'?"Awaiting confirmation":p.status==='confirmed'?"Confirmed":"Cancelled"} · {date(p.at)}</span>{p.note&&<small>{p.note}</small>}</div>{!readOnly&&p.canConfirm&&<button className="st-primary" disabled={busy} onClick={()=>act('confirmPayment',{paymentId:p.id})}>Confirm payment</button>}{!readOnly&&p.status==='pending'&&p.createdBy===userId&&<button disabled={busy} onClick={()=>act('cancelPayment',{paymentId:p.id})}>Cancel record</button>}</div>)}</div>}</section>;}
function People({details=[],funds=[],onPay,canPay,periodLabel,canSeeLifetime=false}){
 const [query,setQuery]=useState(''),[sort,setSort]=useState('closing'),[expanded,setExpanded]=useState('');
 const list=details.filter(p=>(p.playerName||'').toLowerCase().includes(query.toLowerCase())).map(p=>{const f=funds.find(m=>m.uid===p.playerId);return{...p,balance:f?.chips??f?.balance,totalResult:f?.totalResult};}).sort((a,b)=>sort==='name'?a.playerName.localeCompare(b.playerName):sort==='rake'?b.totals.rake-a.totals.rake:sort==='chips'?(b.balance||0)-(a.balance||0):Math.abs(b.closing)-Math.abs(a.closing));
 return <section className="st-panel"><div className="st-section-head"><h3>Player breakdown</h3><span>{details.length} settlement entries</span></div><div className="st-filters"><label className="st-search">Search players<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Player name"/></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="closing">Settlement balance</option><option value="rake">Rake — highest first</option><option value="chips">Chip balance — highest first</option><option value="name">Name</option></select></label></div><div className="st-scroll"><table><thead><tr><th>Player</th><th>Balance and profit/loss</th><th>Rake</th><th>Rakeback</th><th>Settlement balance</th><th>Actions</th></tr></thead><tbody>{list.map(p=>{const key=JSON.stringify([p.agentId,p.playerId]);return <React.Fragment key={key}><tr><td><button className="st-link" aria-expanded={expanded===key} onClick={()=>setExpanded(expanded===key?'':key)}>{p.playerName}</button></td><td><FundsResult chips={p.balance} result={p.totals.result} totalResult={p.totalResult} canSeeLifetime={canSeeLifetime} periodLabel={periodLabel}/></td><td><Amount value={p.totals.rake}/></td><td><Amount value={p.totals.rakeback}/></td><td><Amount value={Math.abs(p.closing)}/><small>{p.closing<0?"Player pays":p.closing>0?"Player receives":"Balanced"}</small></td><td>{canPay(p)&&<button onClick={()=>onPay({type:'player',agentId:p.agentId,playerId:p.playerId,name:p.playerName})}>Record payment</button>}</td></tr>{expanded===key&&<tr><td colSpan="6"><Breakdown opening={p.opening} activity={p.activity} paid={p.paid}/><TableRows rows={p.rows} financial/></td></tr>}</React.Fragment>;})}</tbody></table></div>{!list.length&&<p className="st-empty">No players with activity in the selected cycle.</p>}</section>;
}
function CycleControls({data,act,busy}){
 const open=data.cycles.find(c=>c.id===data.currentCycleId);
 return <section className="st-panel"><h3>Cycle management</h3><p className="st-muted">Cycles never close or reset automatically. Only a manager can close the current cycle. Chip balances and history are preserved.</p>{open&&<p>Current cycle started: <strong>{date(open.startAt)}</strong> · Open until manually closed</p>}<div className="st-actions"><button disabled={busy} onClick={()=>{if(global.confirm("Close this cycle and open the next one now? The closed report, chip balances and history will be preserved."))act('close');}}>Close cycle now</button><button disabled={busy||!open||open.number<=1} onClick={()=>{if(global.confirm("Reopen the previous cycle? This is only possible while the new cycle is empty."))act('reopen');}}>Reopen previous cycle</button>{data.cycle.status==='closed'&&<button disabled={busy} onClick={()=>{if(global.confirm("Lock this cycle? It cannot be reopened after locking."))act('lock',{cycleId:data.cycle.id});}}>Lock selected cycle</button>}</div></section>;
}
function Archive({call,clubId}){const [data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{let live=true;call('pkSettlementArchive',{clubId}).then(r=>live&&setData(r)).catch(e=>live&&setError(settlementError(e)));return()=>{live=false;};},[clubId]);return <section className="st-panel"><h3>Balances saved before the new cycle</h3><p className="st-muted">A snapshot of balances at the transition. Original data and game history are preserved. These amounts are not the opening balance of the new cycle.</p>{error&&<p role="alert">{error}</p>}{data?<><p>{date(data.at)}</p><div className="st-scroll"><table><thead><tr><th>Name</th><th>Saved balance</th><th>Previous cycle result</th><th>Chips including tables</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.uid}><td>{r.name}</td><td><Amount value={Math.round(r.balance*100)}/></td><td><Amount value={Math.round(r.result*100)} signed/></td><td><Amount value={Math.round(r.chips*100)}/></td></tr>)}</tbody></table></div></>:<p role="status">Loading saved balances…</p>}</section>;}
function CyclePicker({data,cycleId,setCycleId}){return <label>Cycle<select aria-label="Select cycle" value={cycleId||data.currentCycleId} onChange={e=>setCycleId(e.target.value)}>{data.cycles.map(c=><option key={c.id} value={c.id}>{c.legacy?"Cycle open before the transition":"Cycle "+c.number} · {status[c.status]}</option>)}{data.role==='owner'&&<option value="all">All cycles since the transition</option>}</select></label>;}
function LegacyCurrent({data,cycleId,setCycleId,act,busy,retry}){
 const [query,setQuery]=useState(''),[sort,setSort]=useState('chips');
 const r=data.legacyReport,t=r.totals,staff=data.role!=='player',owner=data.role==='owner',range=data.dateRange,closed=!range&&data.cycle.status!=='open',periodLabel=range?"in selected dates":closed?"in selected cycle":"in current cycle";
 const rows=r.players.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='result'?b.result-a.result:sort==='rake'?b.rake-a.rake:b.chips-a.chips);
 return <><header className="st-toolbar">{!range&&data.cycles.length>0&&<CyclePicker data={data} cycleId={cycleId} setCycleId={setCycleId}/>}<div className="st-period"><strong>{range?"Date range · Read only":closed?"Previous cycle · Closed":"Current cycle · Open"}</strong><span>{range?rangeDates(range):<>{date(data.cycle.startAt)} – {closed?date(data.cycle.endAt):"Open until manually closed"}</>}</span></div><button disabled={busy} onClick={retry}>Refresh</button></header><section className="st-panel"><h2>{range?"Recorded results in selected dates":closed?"Cycle report saved at closing":"Your current settlement"}</h2><p className="st-muted">{range?"Read-only report of cash-outs and completed tournaments recorded within the selected dates. Games still in progress are excluded. Amounts follow the recording date. Use a saved cycle report to review its final settlement. The current cycle and all balances stay unchanged.":closed?"This report was saved when the cycle closed. Original balances and history have been preserved.":"This cycle stays open until a manager closes it manually. Completed hands count even while a session is still open. An unfinished hand counts after it finishes."}</p><div className="st-net"><span>{owner?"All club players":staff?"My players":"My chips, including tables"}</span><FundsResult chips={t.chips} result={t.result} totalResult={t.totalResult} canSeeLifetime={owner} periodLabel={periodLabel} balanceLabel={closed?'Chips at closing':'Current balance'}/><small>Profit/loss {periodLabel}. Chip top-ups are not profit.</small></div><div className="st-metrics"><Metric label="Wallet chips" value={t.balance}/><Metric label="Chips at tables" value={t.onTables}/>{staff&&<><Metric label={range?"Rake generated in selected dates":"Rake generated this cycle"} value={t.rake}/><Metric label={owner?"Recorded agent commissions":"My recorded commission"} value={t.commission}/></>}</div>{staff&&<p className="st-muted">Commissions reflect amounts recorded in the displayed period. Rake is already included in game results.</p>}</section>
 {owner&&<section className="st-panel"><h3>Agents {periodLabel}</h3><div className="st-scroll"><table><thead><tr><th>Agent</th><th>Balance and profit/loss</th><th>Rake</th><th>Commission</th><th>{range?'Club settlement from selected dates':'Club settlement from cycle activity'}</th></tr></thead><tbody>{r.agents.map(a=><tr key={a.uid}><td>{a.name}</td><td><FundsResult chips={a.chips} result={a.result} totalResult={a.totalResult} canSeeLifetime={owner} periodLabel={periodLabel} balanceLabel={closed?'Chips at closing':'Current balance'}/></td><td><Amount value={a.rake}/></td><td><Amount value={a.commission}/></td><td><Amount value={Math.abs(a.toClub)}/><small>{a.toClub>0?"Agent pays the club":a.toClub<0?"Club pays the agent":"Balanced"} · After commission</small></td></tr>)}</tbody></table></div></section>}
 {data.role==='agent'&&<section className="st-panel"><h3>{range?'Club settlement from selected dates':'Club settlement from cycle activity'}</h3><strong><Amount value={Math.abs(t.toClub)}/></strong><p>{t.toClub>0?"Agent pays the club":t.toClub<0?"Club pays the agent":"Balanced"} · After recorded commission</p></section>}
 {staff&&<section className="st-panel"><h3>Player breakdown</h3><div className="st-filters"><label className="st-search">Search players<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Player name"/></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="chips">Chip amount</option><option value="rake">Rake amount</option><option value="result">{range?"Result in selected dates":"Cycle result"}</option><option value="name">Name</option></select></label></div><div className="st-scroll"><table><thead><tr><th>Player</th><th>Balance and profit/loss</th><th>{range?"Rake in selected dates":"Cycle rake"}</th></tr></thead><tbody>{rows.map(p=><tr key={p.uid}><td>{p.name}</td><td><FundsResult chips={p.chips} result={p.result} totalResult={p.totalResult} canSeeLifetime={owner} periodLabel={periodLabel} balanceLabel={closed?'Chips at closing':'Current balance'}/></td><td><Amount value={p.rake}/></td></tr>)}</tbody></table></div>{!rows.length&&<p className="st-empty">No players found.</p>}</section>}
 {data.canClose&&!data.readOnly&&!range&&<section className="st-panel"><h3>Close the current cycle</h3><p>When settlement is complete, save this cycle as closed and start the next one at zero. Chip balances and history will stay the same.</p><button className="st-primary" disabled={busy} onClick={()=>{if(global.confirm("Close the current cycle and start the next one at zero? The current report will be saved for reference. Chip balances and history will stay the same. Debts and credits from this cycle will not carry over."))act('closeLegacy');}}>Close cycle and start next</button></section>}</>;
}
function Settlement({user,clubId,call,showToast=()=>{}}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[cycleId,setCycleId]=useState(''),[attempt,setAttempt]=useState(0),[busy,setBusy]=useState(false),[payment,setPayment]=useState(null),[tab,setTab]=useState('report'),[remark,setRemark]=useState(''),[range,setRange]=useState(null);
 const actionRef=useRef(false);
 useEffect(()=>{let live=true,inFlight=false;setData(null);setError('');const load=()=>{if(!live||inFlight)return;inFlight=true;return call('pkSettlementReport',{clubId,...(range?range:cycleId?{cycleId}:{})}).then(r=>{if(range&&(!r.readOnly||r.dateRange?.fromAt!==range.fromAt||r.dateRange?.toAt!==range.toAt))throw Error('The requested date range could not be verified. Please try again.');if(live){setData(r);setError('');}}).catch(e=>{if(live)setError(settlementError(e));}).finally(()=>{inFlight=false;});};load();const timer=range?null:setInterval(load,30000);return()=>{live=false;if(timer)clearInterval(timer);};},[user.uid,user.role,clubId,cycleId,range,attempt]);
 const applyRange=value=>{setRange(value);setCycleId('');setPayment(null);setTab('report');setRemark('');};
 const currentCycle=()=>{setRange(null);setCycleId('');setPayment(null);setTab('report');setRemark('');};
 const act=async(action,fields={})=>{if(actionRef.current||range||data?.readOnly)return false;actionRef.current=true;setBusy(true);setError('');try{const result=await call('pkSettlement',{clubId,action,...fields});if(result.cycleId)setCycleId(result.cycleId);setAttempt(n=>n+1);if(typeof global.dispatchEvent==='function'&&typeof global.Event==='function')global.dispatchEvent(new global.Event('pk-club-changed'));showToast("Changes saved",'success');return true;}catch(e){setError(settlementError(e,"Could not save changes"));return false;}finally{actionRef.current=false;setBusy(false);}};
 const errorBox=error&&<div role="alert" className="st-error">{error}<button onClick={()=>setAttempt(n=>n+1)}>Try again</button></div>;
 if(!data)return <div className="settlement-app" dir="ltr">{errorBox||<p role="status">Loading your settlement…</p>}{range&&<button onClick={currentCycle}>Back to current cycle</button>}</div>;
 const reportDates=<ReportDates data={data} range={range} onRange={applyRange} onCurrent={currentCycle} busy={busy}/>;
 if(data.needsPeriodStart)return <div className="settlement-app" dir="ltr">{errorBox}{reportDates}<PeriodStartRequired data={data} act={act} busy={busy}/></div>;
 if(data.legacy)return <div className="settlement-app" dir="ltr">{errorBox}{reportDates}<LegacyCurrent data={data} cycleId={cycleId} setCycleId={setCycleId} act={act} busy={busy} retry={()=>setAttempt(n=>n+1)}/></div>;
 if(!data.active)return <div className="settlement-app" dir="ltr">{errorBox}<p role="alert">The current cycle report is unavailable. Refresh to try again.</p><button onClick={()=>setAttempt(n=>n+1)}>Refresh</button></div>;
 const owner=data.role==='owner',agent=data.role==='agent',p=data.player,a=data.agent,c=data.club?.totals,selectedCurrent=!range&&!data.readOnly&&data.cycle.id===data.currentCycleId,periodLabel=data.cycle.id==='all'?"across selected cycles":selectedCurrent?"in current cycle":"in selected cycle";
 const canPay=pair=>selectedCurrent&&(pair.agentId===user.uid||pair.playerId===user.uid||pair.agentId==='club'&&data.clubPartyId===user.uid);
 return <div className="settlement-app" dir="ltr">{errorBox}{reportDates}<header className="st-toolbar"><CyclePicker data={data} cycleId={cycleId} setCycleId={setCycleId}/><div className="st-period"><strong>{status[data.cycle.status]}</strong><span>{date(data.cycle.startAt)} – {data.cycle.status==='open'?'Open until manually closed':date(data.cycle.endAt)}</span></div><button onClick={()=>setAttempt(n=>n+1)} disabled={busy}>Refresh</button></header><nav className="st-tabs" aria-label="Settlement information"><button aria-pressed={tab==='report'} onClick={()=>setTab('report')}>Settlement report</button>{owner&&<button aria-pressed={tab==='cycles'} onClick={()=>setTab('cycles')}>Cycle management</button>}<button aria-pressed={tab==='archive'} onClick={()=>setTab('archive')}>Pre-transition balances</button></nav>{tab==='archive'?<Archive call={call} clubId={clubId}/>:tab==='cycles'&&owner?<CycleControls data={data} act={act} busy={busy}/>:<>
 <p className="st-muted st-method">{!selectedCurrent&&<strong>Historical report · Read only. </strong>}Completed hands count toward the current cycle even while a session remains open. An unfinished hand counts after it finishes. Pending payments do not change the amount due.</p>
 {(owner||agent)&&data.currentTotals&&<section className="st-panel st-funds-panel"><h3>{owner?"All club players":"My players"}</h3><FundsResult chips={data.currentTotals.chips} result={owner?c.playersResult:a.playersResult} totalResult={data.currentTotals.totalResult} canSeeLifetime={owner} periodLabel={periodLabel}/></section>}
 {owner?<><Net value={c.closing} kind="club"/><div className="st-metrics"><Metric label={"Player results "+periodLabel} value={c.playersResult} signed/><Metric label="Rake generated" value={c.rake}/><Metric label="Agent commissions" value={c.commission+c.leadsIncome}/><Metric label="Hands" value={c.hands} plain/></div><section className="st-panel"><h3>Agent settlement</h3><div className="st-scroll"><table><thead><tr><th>Agent</th><th>Player results</th><th>Rake</th><th>Commission</th><th>Balance with club</th><th>Payment</th></tr></thead><tbody>{data.agents.map(x=><tr key={x.agentId}><td><details><summary>{x.agentName}</summary><Breakdown opening={x.opening} activity={x.toClub} paid={x.paid} kind="agent"/></details></td><td><Amount value={x.playersResult} signed/></td><td><Amount value={x.rake}/></td><td><Amount value={x.commission+x.leadsIncome}/></td><td><Amount value={Math.abs(x.closing)}/><small>{x.closing>0?"Agent pays the club":x.closing<0?"Club pays the agent":"Balanced"}</small></td><td>{selectedCurrent&&user.uid===data.clubPartyId&&<button onClick={()=>setPayment({type:'agent',agentId:x.agentId,name:x.agentName})}>Record payment</button>}</td></tr>)}</tbody></table></div>{!data.agents.length&&<p className="st-empty">No agent activity in this cycle.</p>}</section></>:agent?<><Net value={a.closing}/><Breakdown opening={a.opening} activity={a.toClub} paid={a.paid} kind="agent"/><div className="st-metrics"><Metric label={"My players’ results "+periodLabel} value={a.playersResult} signed/><Metric label="Rake generated" value={a.rake}/><Metric label="My commission" value={a.commission}/><Metric label="My earnings after rakeback" value={a.earnings}/></div>{selectedCurrent&&<button className="st-primary" onClick={()=>setPayment({type:'agent',agentId:user.uid,name:"Club"})}>Record payment with club</button>}{a.leads.length>0&&<section className="st-panel"><h3>Referral commissions</h3>{a.leads.map(l=><div className="st-payment" key={l.playerId}><span>{l.playerName}</span><Amount value={l.commission}/></div>)}</section>}</>:<><section className="st-panel st-funds-panel"><h3>My balance and profit/loss</h3><FundsResult chips={data.chips??data.balance} result={p.totals.result} periodLabel={periodLabel}/></section><Net value={p.closing} kind="player"/><Breakdown opening={p.opening} activity={p.totals.result+(p.rakebackTotal||0)} paid={p.paid}/><div className="st-metrics"><Metric label="Hands played" value={p.totals.hands} plain/>{p.hasRakeback&&<Metric label="My rakeback" value={p.rakebackTotal}/>}</div><section className="st-panel"><h3>My games</h3><TableRows rows={p.rows}/></section>{p.counterparties.map(x=><div className="st-payment" key={x.id}><span>{x.name==='club'?"Club":x.name} · {x.closing<0?"You pay":"You receive"} <Amount value={Math.abs(x.closing)}/></span>{selectedCurrent&&<button onClick={()=>setPayment({type:'player',agentId:x.id,playerId:user.uid,name:x.name==='club'?"Club":x.name})}>Record payment</button>}</div>)}</>}
 {(owner||agent)&&<p className="st-muted">Rake is already included in game results. The amount due to or from the club is calculated after commission; do not deduct rake again.</p>}
 {(owner||agent)&&<People details={data.details} funds={data.funds} onPay={setPayment} canPay={canPay} periodLabel={periodLabel} canSeeLifetime={owner}/>}
 <Payments items={data.payments} act={act} busy={busy} userId={user.uid} readOnly={!selectedCurrent}/>
 {selectedCurrent&&data.cycle.status!=='locked'&&<section className="st-panel"><h3>Approve report or add a note</h3><label>Report note<textarea maxLength="1000" value={remark} onChange={e=>setRemark(e.target.value)} placeholder="Leave a note for the club manager"/></label><div className="st-actions"><button className="st-primary" disabled={busy} onClick={()=>act('approve',{cycleId:data.cycle.id,approved:true,remark})}>Approve report</button><button disabled={busy||!remark.trim()} onClick={()=>act('approve',{cycleId:data.cycle.id,approved:false,remark})}>Send note</button></div>{data.approvals.map(x=><p key={x.uid} className="st-muted">{x.uid===user.uid?"My approval":x.uid}: {x.approved?"Confirmed":"Note"} · {x.remark} · {date(x.at)}</p>)}</section>}
 </>}{payment&&<PaymentForm spec={payment} userId={user.uid} clubPartyId={data.clubPartyId} act={act} onClose={()=>setPayment(null)} busy={busy} error={error}/>}</div>;
}
function TermsEditor({member,agents,manager,save,busy,onClose}){
 const [draft,setDraft]=useState({primaryAgentId:member.primaryAgentId||'',secondaryAgentId:member.secondaryAgentId||'',secondaryPct:member.secondaryPct||0,rakebackPct:member.rakebackPct||0,agentType:member.agentType||'rake',agentPct:member.agentPct??member.defaultAgentPct??50});
 const field=(key,value)=>setDraft(p=>({...p,[key]:value})),isAgent=['agent','manager','club_owner'].includes(member.role);
 return <form className="st-panel st-terms-editor" onSubmit={async e=>{e.preventDefault();const patch=manager?{primaryAgentId:draft.primaryAgentId,secondaryAgentId:draft.secondaryAgentId,secondaryPct:Number(draft.secondaryPct),rakebackPct:Number(draft.rakebackPct),...(isAgent?{agentType:draft.agentType,agentPct:Number(draft.agentPct)}:{})}:{rakebackPct:Number(draft.rakebackPct)};if(await save(member.uid,patch))onClose();}}><h3>Terms · {member.name}</h3><p className="st-muted">New terms apply to sessions recorded after saving. Previous sessions keep their original terms.</p><div className="st-filters">{manager&&<><label>Primary agent<select value={draft.primaryAgentId} onChange={e=>field('primaryAgentId',e.target.value)}><option value="">Directly with club</option>{agents.filter(a=>a.uid!==member.uid).map(a=><option key={a.uid} value={a.uid}>{a.name}</option>)}</select></label><label>Secondary agent<select value={draft.secondaryAgentId} onChange={e=>field('secondaryAgentId',e.target.value)}><option value="">None</option>{agents.filter(a=>a.uid!==member.uid&&a.uid!==draft.primaryAgentId).map(a=><option key={a.uid} value={a.uid}>{a.name}</option>)}</select></label>{draft.secondaryAgentId&&<label>Referral commission (%)<input type="number" min="0" max="100" step="0.01" value={draft.secondaryPct} onChange={e=>field('secondaryPct',e.target.value)}/></label>}</>}<label>Player rakeback (%)<input type="number" min="0" max="100" step="0.01" value={draft.rakebackPct} onChange={e=>field('rakebackPct',e.target.value)}/></label>{manager&&isAgent&&<><label>Agreement type<select value={draft.agentType} onChange={e=>field('agentType',e.target.value)}><option value="rake">Percentage of rake</option><option value="result">Percentage of player results</option></select></label><label>Agent share (%)<input type="number" min="0" max="100" step="0.01" value={draft.agentPct} onChange={e=>field('agentPct',e.target.value)}/></label></>}</div><div className="st-actions"><button className="st-primary" disabled={busy}>Save terms</button><button type="button" disabled={busy} onClick={onClose}>Cancel</button></div></form>;
}
function SettlementMembers({clubId,call}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[edit,setEdit]=useState(null),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState(0);const lock=useRef(false);
 useEffect(()=>{let alive=true;call('pkSettlementTerms',{clubId,action:'list'}).then(r=>{if(alive){setData(r);setError('');}}).catch(e=>alive&&setError(settlementError(e,'Could not load member terms')));return()=>{alive=false;};},[clubId,attempt]);
 const save=async(targetUid,patch)=>{if(lock.current)return false;lock.current=true;setBusy(true);try{await call('pkSettlementTerms',{clubId,targetUid,patch});setAttempt(n=>n+1);global.dispatchEvent(new Event('pk-club-changed'));return true;}catch(e){setError(settlementError(e,'Could not save member terms'));return false;}finally{lock.current=false;setBusy(false);}};
 const agents=(data?.members||[]).filter(m=>['agent','manager','club_owner'].includes(m.role)&&m.status==='approved');
 return <section className="settlement-app" dir="ltr" id="bo-terms"><div className="st-panel"><h3>Agents and rates</h3>{error&&<div role="alert" className="st-error">{error}<button onClick={()=>setAttempt(n=>n+1)}>Try again</button></div>}{!data&&!error?<p role="status">Loading terms…</p>:data&&<><label>Search club members<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Player or agent name"/></label><div className="st-scroll"><table><thead><tr><th>Name</th><th>Primary agent</th><th>Rakeback</th><th>Edit</th></tr></thead><tbody>{data.members.filter(m=>m.status==='approved'&&m.name.toLowerCase().includes(search.toLowerCase())).map(m=><tr key={m.uid}><td>{m.name}<small>{['agent','manager','club_owner'].includes(m.role)?"Agent / Manager":"Player"}</small></td><td>{agents.find(a=>a.uid===m.primaryAgentId)?.name||"Club"}</td><td>{m.rakebackPct||0}%</td><td><button onClick={()=>setEdit(m)}>Terms</button></td></tr>)}</tbody></table></div></>}</div>{edit&&<TermsEditor key={edit.uid} member={edit} agents={agents} manager={data.role==='owner'} save={save} busy={busy} onClose={()=>setEdit(null)}/>}</section>;
}
global.PokerSettlement={Settlement,SettlementMembers,Amount,money};
})(window);
